/**
 * Campus Workspace — Export Service
 * Centralised, watermarked export for all document types.
 * NEVER renames HTML/JSON as DOCX/XLSX/PPTX.
 */

import { Response } from 'express';
import { prisma } from '../../lib/prisma';
import { PdfWatermarkService } from '../../services/pdf-watermark.service';
import { WorkspacePermissionService } from './workspace.permission.service';
import { ForbiddenException, NotFoundException } from '../../utils/exceptions';

export class WorkspaceExportService {
  static async export(
    documentId: string,
    format: string,
    userId: string,
    userRole: string,
    userDepartmentId: string | undefined,
    res: Response
  ) {
    const perms = await WorkspacePermissionService.resolvePermissions(documentId, userId, userRole, userDepartmentId);
    if (!perms.canExport && !perms.canDownload) throw new ForbiddenException('Export access denied.');

    const doc = await prisma.campusOfficeDocument.findUnique({ where: { id: documentId } });
    if (!doc) throw new NotFoundException('Document not found.');

    let content: any;
    try {
      content = JSON.parse(doc.contentJson);
    } catch {
      content = {};
    }

    const dateStr = new Date().toISOString().slice(0, 10);
    const safeName = doc.title.replace(/[^a-zA-Z0-9_\- ]/g, '').trim().replace(/\s+/g, '_') || 'document';

    switch (format.toLowerCase()) {
      case 'pdf':
        return this.exportPDF(doc, content, safeName, dateStr, res);
      case 'docx':
        return this.exportDOCX(doc, content, safeName, dateStr, res);
      case 'xlsx':
        if (doc.type !== 'SHEET') throw new Error('XLSX export only available for sheets.');
        return this.exportXLSX(doc, content, safeName, dateStr, res);
      case 'csv':
        if (doc.type !== 'SHEET') throw new Error('CSV export only available for sheets.');
        return this.exportCSV(doc, content, safeName, dateStr, res);
      case 'pptx':
        if (doc.type !== 'SLIDE') throw new Error('PPTX export only available for presentations.');
        return this.exportPPTX(doc, content, safeName, dateStr, res);
      default:
        res.status(400).json({ message: `Unsupported export format: ${format}` });
    }
  }

  // ─── PDF Export (with watermark) ────────────────────────────────────────────

  private static async exportPDF(doc: any, content: any, safeName: string, dateStr: string, res: Response) {
    const PDFDocument = (await import('pdfkit')).default;

    const pdfDoc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_${dateStr}.pdf"`);
    pdfDoc.pipe(res);

    // Apply institutional watermark
    PdfWatermarkService.applyWatermark(pdfDoc);

    // Branding header
    const settings = await prisma.systemSetting.findMany({
      where: { key: { in: ['COLLEGE_NAME', 'COLLEGE_ADDRESS'] } },
    });
    const settingsMap = Object.fromEntries(settings.map((s) => [s.key, s.value]));
    const collegeName = settingsMap['COLLEGE_NAME'] || 'CampusOS Institution';

    pdfDoc.fontSize(14).font('Helvetica-Bold').text(collegeName, { align: 'center' });
    if (settingsMap['COLLEGE_ADDRESS']) {
      pdfDoc.fontSize(9).font('Helvetica').text(settingsMap['COLLEGE_ADDRESS'], { align: 'center' });
    }
    pdfDoc.moveDown(0.5);
    pdfDoc.moveTo(50, pdfDoc.y).lineTo(545, pdfDoc.y).stroke('#ccc');
    pdfDoc.moveDown(0.5);

    // Title
    pdfDoc.fontSize(16).font('Helvetica-Bold').text(doc.title, { align: 'center' });
    pdfDoc.moveDown(0.3);
    pdfDoc.fontSize(9).font('Helvetica').fillColor('#666').text(`Status: ${doc.status} | Version: ${doc.currentVersion} | Date: ${dateStr}`, { align: 'center' });
    pdfDoc.fillColor('#000').moveDown(1);

    // Content
    if (doc.type === 'DOC' || doc.type === 'NOTE') {
      this.renderTipTapToPDF(pdfDoc, content);
    } else if (doc.type === 'SHEET') {
      this.renderSheetToPDF(pdfDoc, content);
    } else if (doc.type === 'SLIDE') {
      this.renderSlidesToPDF(pdfDoc, content);
    } else if (doc.type === 'REPORT') {
      this.renderReportToPDF(pdfDoc, content);
    } else {
      pdfDoc.fontSize(10).text(JSON.stringify(content, null, 2));
    }

    // Footer
    pdfDoc.fontSize(8).fillColor('#888').text(
      `Generated by Campus Workspace | ${collegeName} | ${dateStr}`,
      50, pdfDoc.page.height - 40,
      { align: 'center', width: 495 }
    );

    pdfDoc.end();
  }

  private static renderTipTapToPDF(doc: PDFKit.PDFDocument, content: any) {
    if (!content?.content) {
      doc.fillColor('#999').fontSize(10).text('(Empty document)');
      doc.fillColor('#000');
      return;
    }

    const renderNode = (node: any) => {
      if (!node) return;
      if (node.type === 'heading') {
        const sizes: Record<number, number> = { 1: 18, 2: 16, 3: 14, 4: 12 };
        const size = sizes[node.attrs?.level || 1] || 12;
        const text = node.content?.map((n: any) => n.text || '').join('') || '';
        doc.fontSize(size).font('Helvetica-Bold').text(text);
        doc.moveDown(0.3);
      } else if (node.type === 'paragraph') {
        const text = node.content?.map((n: any) => n.text || '').join('') || '';
        doc.fontSize(10).font('Helvetica').text(text || ' ', { paragraphGap: 4 });
        doc.moveDown(0.2);
      } else if (node.type === 'bulletList' || node.type === 'orderedList') {
        node.content?.forEach((item: any, idx: number) => {
          const bullet = node.type === 'orderedList' ? `${idx + 1}.` : '•';
          const text = item.content?.[0]?.content?.map((n: any) => n.text || '').join('') || '';
          doc.fontSize(10).text(`${bullet} ${text}`, { indent: 20 });
        });
        doc.moveDown(0.3);
      } else if (node.type === 'blockquote') {
        doc.save().fillColor('#666');
        const text = node.content?.map((n: any) => n.content?.map((nn: any) => nn.text || '').join('')).join('\n') || '';
        doc.fontSize(10).text(text, { indent: 20 });
        doc.restore().moveDown(0.2);
      } else if (node.type === 'horizontalRule') {
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#ccc');
        doc.moveDown(0.3);
      } else if (node.content) {
        node.content.forEach(renderNode);
      }
    };

    content.content?.forEach(renderNode);
  }

  private static renderSheetToPDF(doc: PDFKit.PDFDocument, content: any) {
    const sheets = content?.sheets || [];
    sheets.forEach((sheet: any, sheetIdx: number) => {
      if (sheetIdx > 0) doc.addPage();
      doc.fontSize(12).font('Helvetica-Bold').text(sheet.name || `Sheet ${sheetIdx + 1}`);
      doc.moveDown(0.3);

      const cells = sheet.cells || {};
      const rows: Record<number, Record<number, string>> = {};
      Object.entries(cells).forEach(([key, val]: [string, any]) => {
        const match = key.match(/^([A-Z]+)(\d+)$/);
        if (match) {
          const col = match[1].charCodeAt(0) - 65;
          const row = parseInt(match[2]) - 1;
          if (!rows[row]) rows[row] = {};
          rows[row][col] = String(val?.value ?? val ?? '');
        }
      });

      const rowNums = Object.keys(rows).map(Number).sort((a, b) => a - b);
      if (rowNums.length === 0) {
        doc.fontSize(9).fillColor('#999').text('(Empty sheet)');
        doc.fillColor('#000');
        return;
      }

      const maxCol = Math.max(...Object.values(rows).map((r) => Math.max(...Object.keys(r).map(Number), 0)));
      const colW = Math.min(80, (495) / (maxCol + 1));

      rowNums.forEach((rowIdx, ri) => {
        if (ri > 50) { doc.fontSize(8).text('... (truncated at 50 rows for PDF)'); return; }
        const y = doc.y;
        const row = rows[rowIdx];
        for (let c = 0; c <= maxCol; c++) {
          const x = 50 + c * colW;
          const cellText = (row[c] || '').slice(0, 20);
          doc.fontSize(8).text(cellText, x, y, { width: colW - 2, lineBreak: false });
        }
        doc.y = y + 14;
      });
    });
  }

  private static renderSlidesToPDF(doc: PDFKit.PDFDocument, content: any) {
    const slides = content?.slides || [];
    slides.forEach((slide: any, idx: number) => {
      if (idx > 0) doc.addPage();
      doc.fontSize(10).fillColor('#666').text(`Slide ${idx + 1}`, { align: 'right' });
      doc.fillColor('#000');
      slide.elements?.forEach((el: any) => {
        if (el.type === 'text') {
          doc.fontSize(el.fontSize || 12).text(el.content || '', { continued: false });
          doc.moveDown(0.2);
        }
      });
      if (slide.notes) {
        doc.moveDown(1).fontSize(8).fillColor('#888').text(`Notes: ${slide.notes}`).fillColor('#000');
      }
    });
  }

  private static renderReportToPDF(doc: PDFKit.PDFDocument, content: any) {
    const sections = content?.sections || [];
    sections.forEach((section: any) => {
      if (section.title) {
        doc.fontSize(13).font('Helvetica-Bold').text(section.title);
        doc.moveDown(0.3);
      }
      if (section.content) {
        doc.fontSize(10).font('Helvetica').text(section.content);
        doc.moveDown(0.3);
      }
      if (section.metrics) {
        section.metrics.forEach((m: any) => {
          doc.fontSize(10).text(`• ${m.label}: ${m.value}`, { indent: 15 });
        });
        doc.moveDown(0.3);
      }
      doc.moveDown(0.3);
    });
  }

  // ─── DOCX Export ─────────────────────────────────────────────────────────────

  private static async exportDOCX(doc: any, content: any, safeName: string, dateStr: string, res: Response) {
    const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx');

    const children: any[] = [];

    // Title
    children.push(new Paragraph({ text: doc.title, heading: HeadingLevel.HEADING_1 }));

    const renderTipTapToDocx = (node: any): any[] => {
      if (!node?.content) return [];
      const paras: any[] = [];
      node.content.forEach((n: any) => {
        if (n.type === 'heading') {
          const level: Record<number, any> = {
            1: HeadingLevel.HEADING_1, 2: HeadingLevel.HEADING_2,
            3: HeadingLevel.HEADING_3, 4: HeadingLevel.HEADING_4,
          };
          paras.push(new Paragraph({
            text: n.content?.map((c: any) => c.text || '').join('') || '',
            heading: level[n.attrs?.level || 1] || HeadingLevel.HEADING_1,
          }));
        } else if (n.type === 'paragraph') {
          const runs = (n.content || []).map((inline: any) => new TextRun({
            text: inline.text || '',
            bold: inline.marks?.some((m: any) => m.type === 'bold'),
            italics: inline.marks?.some((m: any) => m.type === 'italic'),
            underline: inline.marks?.some((m: any) => m.type === 'underline') ? ({ type: 'single' } as any) : undefined,
          }));
          paras.push(new Paragraph({ children: runs }));
        } else if (n.type === 'bulletList') {
          n.content?.forEach((item: any) => {
            const text = item.content?.[0]?.content?.map((c: any) => c.text || '').join('') || '';
            paras.push(new Paragraph({ text, bullet: { level: 0 } }));
          });
        }
      });
      return paras;
    };

    children.push(...renderTipTapToDocx(content));

    // Footer
    children.push(new Paragraph({ children: [new TextRun({ text: `Generated by Campus Workspace | ${dateStr}`, color: '999999', size: 16 })] }));

    const docx = new Document({ sections: [{ properties: {}, children }] });

    const buffer = await Packer.toBuffer(docx);
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_${dateStr}.docx"`);
    res.send(buffer);
  }

  // ─── XLSX Export ─────────────────────────────────────────────────────────────

  private static async exportXLSX(doc: any, content: any, safeName: string, dateStr: string, res: Response) {
    const ExcelJS = (await import('exceljs')).default;
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Campus Workspace';
    workbook.created = new Date();

    const sheets = content?.sheets || [{ name: 'Sheet 1', cells: {} }];
    sheets.forEach((sheetData: any) => {
      const sheet = workbook.addWorksheet(sheetData.name || 'Sheet 1');
      const cells = sheetData.cells || {};

      Object.entries(cells).forEach(([cellRef, val]: [string, any]) => {
        const cell = sheet.getCell(cellRef);
        cell.value = val?.value ?? val ?? null;
        if (val?.format) {
          cell.numFmt = val.format;
        }
        if (val?.style?.bold) cell.font = { bold: true };
        if (val?.style?.bg) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: val.style.bg.replace('#', 'FF') } };
      });

      // Column widths
      sheet.columns.forEach((col) => { if (col && !col.width) col.width = 15; });
    });

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_${dateStr}.xlsx"`);
    await workbook.xlsx.write(res);
  }

  // ─── CSV Export ───────────────────────────────────────────────────────────────

  private static exportCSV(doc: any, content: any, safeName: string, dateStr: string, res: Response) {
    const firstSheet = content?.sheets?.[0] || { cells: {} };
    const cells = firstSheet.cells || {};
    const rows: Record<number, Record<number, string>> = {};

    Object.entries(cells).forEach(([key, val]: [string, any]) => {
      const match = key.match(/^([A-Z]+)(\d+)$/);
      if (match) {
        const col = match[1].charCodeAt(0) - 65;
        const row = parseInt(match[2]) - 1;
        if (!rows[row]) rows[row] = {};
        // Sanitize against CSV injection
        let cellVal = String(val?.value ?? val ?? '');
        if (/^[=+\-@|]/.test(cellVal)) cellVal = `'${cellVal}`;
        rows[row][col] = cellVal.includes(',') ? `"${cellVal.replace(/"/g, '""')}"` : cellVal;
      }
    });

    const rowNums = Object.keys(rows).map(Number).sort((a, b) => a - b);
    if (rowNums.length === 0) { res.setHeader('Content-Type', 'text/csv'); return res.send(''); }

    const maxCol = Math.max(...Object.values(rows).map((r) => Math.max(...Object.keys(r).map(Number), 0)));
    const csvLines = rowNums.map((rowIdx) => {
      return Array.from({ length: maxCol + 1 }, (_, c) => rows[rowIdx]?.[c] || '').join(',');
    });

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_${dateStr}.csv"`);
    res.send(csvLines.join('\r\n'));
  }

  // ─── PPTX Export ─────────────────────────────────────────────────────────────

  private static async exportPPTX(doc: any, content: any, safeName: string, dateStr: string, res: Response) {
    const pptxgen = (await import('pptxgenjs')).default;
    const pptx = new pptxgen();

    const slides: any[] = content?.slides || [];
    if (slides.length === 0) {
      const slide = pptx.addSlide();
      slide.addText(doc.title, { x: 1, y: 2.5, w: '80%', fontSize: 36, bold: true, align: 'center' });
    } else {
      slides.forEach((slideData: any) => {
        const slide = pptx.addSlide();
        slideData.elements?.forEach((el: any) => {
          if (el.type === 'text') {
            slide.addText(el.content || '', {
              x: (el.x || 0) / 100,
              y: (el.y || 0) / 100,
              w: (el.width || 80) / 100,
              h: (el.height || 20) / 100,
              fontSize: el.fontSize || 18,
              bold: el.bold,
              color: el.color?.replace('#', '') || '000000',
            });
          }
        });
        if (slideData.notes) {
          slide.addNotes(slideData.notes);
        }
      });
    }

    const buffer = await pptx.write({ outputType: 'nodebuffer' }) as Buffer;
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.presentationml.presentation');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_${dateStr}.pptx"`);
    res.send(buffer);
  }
}
