import {
  Plus,
  Pencil,
  Eye,
  Trash2,
  CheckCircle2,
  XCircle,
  Undo2,
  Upload,
  Download,
  Printer,
  Share2,
  FileSpreadsheet,
  FileText,
  SlidersHorizontal,
  RefreshCw,
  Copy,
  Archive,
  RotateCcw,
  Send,
  Reply,
  Forward,
  UserPlus,
  CalendarClock,
  X,
  Save,
  Search,
} from 'lucide-react';

export const actionIcons = {
  create: Plus,
  edit: Pencil,
  view: Eye,
  delete: Trash2,
  approve: CheckCircle2,
  reject: XCircle,
  return: Undo2,
  upload: Upload,
  download: Download,
  print: Printer,
  share: Share2,
  exportExcel: FileSpreadsheet,
  exportPdf: FileText,
  filter: SlidersHorizontal,
  refresh: RefreshCw,
  duplicate: Copy,
  archive: Archive,
  restore: RotateCcw,
  send: Send,
  reply: Reply,
  forward: Forward,
  assign: UserPlus,
  schedule: CalendarClock,
  cancel: X,
  save: Save,
  search: Search,
};

export type ActionIconKey = keyof typeof actionIcons;
