import {
  LayoutDashboard,
  ClipboardCheck,
  CalendarClock,
  BookOpen,
  FileCheck2,
  BarChart3,
  GraduationCap,
  Users,
  UserRoundCog,
  HeartHandshake,
  CalendarOff,
  ListChecks,
  Megaphone,
  MessageSquare,
  Bell,
  Receipt,
  CreditCard,
  Bus,
  Building2,
  Library,
  Briefcase,
  BadgeCheck,
  BarChart,
  ShieldCheck,
  ScrollText,
  Settings,
  CircleHelp,
  Building,
  UserCheck,
  FileText
} from 'lucide-react';

export const moduleIcons = {
  dashboard: LayoutDashboard,
  attendance: ClipboardCheck,
  timetable: CalendarClock,
  subjects: BookOpen,
  assignments: FileCheck2,
  marks: BarChart3,
  examinations: GraduationCap,
  students: Users,
  faculty: UserRoundCog,
  mentor: HeartHandshake,
  leaveOd: CalendarOff,
  tasks: ListChecks,
  circulars: Megaphone,
  messages: MessageSquare,
  notifications: Bell,
  fees: Receipt,
  payments: CreditCard,
  transport: Bus,
  hostel: Building2,
  library: Library,
  placement: Briefcase,
  internship: BadgeCheck,
  reports: BarChart,
  security: ShieldCheck,
  audit: ScrollText,
  settings: Settings,
  support: CircleHelp,
  institution: Building,
  profile: UserCheck,
  documents: FileText,
};

export type ModuleIconKey = keyof typeof moduleIcons;
