import {
  ShieldAlert,
  Crown,
  ShieldCheck,
  GraduationCap,
  UserPlus,
  Award,
  FileCheck,
  Building2,
  UserCheck,
  HeartHandshake,
  User,
  Users,
  Receipt,
  BookOpen,
  Bus,
  Shield,
  PhoneCall,
  Briefcase,
  Home,
  Building,
} from 'lucide-react';

export const roleIcons = {
  superAdmin: ShieldAlert,
  principal: Crown,
  vicePrincipal: ShieldCheck,
  academicDean: GraduationCap,
  admissionDean: UserPlus,
  iqacDean: Award,
  coe: FileCheck,
  hod: Building2,
  faculty: UserCheck,
  mentor: HeartHandshake,
  student: User,
  parent: Users,
  accountant: Receipt,
  librarian: BookOpen,
  transport: Bus,
  security: Shield,
  reception: PhoneCall,
  placementOfficer: Briefcase,
  hostelWarden: Home,
  officeStaff: Building,
};

export type RoleIconKey = keyof typeof roleIcons;
