import {
  CheckCircle2,
  Clock,
  Loader2,
  XCircle,
  AlertTriangle,
  Info,
  CheckCircle,
  MinusCircle,
  WifiOff,
  CalendarOff,
  BadgeCheck,
  Sun,
  Ban,
  Check,
  X,
  Lock,
  LockOpen,
  ShieldCheck,
  ShieldAlert,
  Palmtree,
  Clock3,
  Laptop,
  Stethoscope,
  Bell,
  Megaphone,
  Siren,
  FileText,
  ListChecks,
  AlertCircle,
  Calendar,
  FileCheck,
  Briefcase,
  BookOpen,
  CreditCard,
} from 'lucide-react';

export const statusIcons = {
  completed: CheckCircle2,
  pending: Clock,
  inProgress: Loader2,
  rejected: XCircle,
  warning: AlertTriangle,
  info: Info,
  available: CheckCircle,
  busy: MinusCircle,
  offline: WifiOff,
  leave: CalendarOff,
  od: BadgeCheck,
  holiday: Sun,
  suspended: Ban,
  active: Check,
  inactive: X,
  locked: Lock,
  unlocked: LockOpen,
  verified: ShieldCheck,
  unverified: ShieldAlert,
};

export const attendanceIcons = {
  present: CheckCircle2,
  absent: XCircle,
  late: Clock,
  leave: CalendarOff,
  od: BadgeCheck,
  holiday: Palmtree,
  halfDay: Clock3,
  remote: Laptop,
  medicalLeave: Stethoscope,
};

export const notificationIcons = {
  general: Bell,
  reminder: Clock,
  announcement: Megaphone,
  emergency: Siren,
  circular: FileText,
  task: ListChecks,
  complaint: AlertCircle,
  meeting: Calendar,
  exam: FileCheck,
  placement: Briefcase,
  assignment: BookOpen,
  feeReminder: CreditCard,
};

export type StatusIconKey = keyof typeof statusIcons;
export type AttendanceIconKey = keyof typeof attendanceIcons;
export type NotificationIconKey = keyof typeof notificationIcons;
