export const QUERY_KEYS = {
  auth: {
    me: ['auth', 'me'] as const,
    workspace: ['auth', 'workspace'] as const,
  },
  student: {
    dashboard: ['student', 'dashboard'] as const,
    profile: ['student', 'profile'] as const,
    leaveList: ['student', 'leave'] as const,
    odList: ['student', 'od'] as const,
    assignments: ['student', 'assignments'] as const,
    attendance: ['student', 'attendance'] as const,
    marks: ['student', 'marks'] as const,
    timetable: ['student', 'timetable'] as const,
    circulars: ['student', 'circulars'] as const,
    complaints: ['student', 'complaints'] as const,
    tasks: ['student', 'tasks'] as const,
  },
  faculty: {
    dashboard: ['faculty', 'dashboard'] as const,
    attendance: ['faculty', 'attendance'] as const,
    classes: ['faculty', 'classes'] as const,
    assignments: ['faculty', 'assignments'] as const,
    marks: ['faculty', 'marks'] as const,
    tasks: ['faculty', 'tasks'] as const,
    leave: ['faculty', 'leave'] as const,
    mentorStudents: ['faculty', 'mentor', 'students'] as const,
    mentorApprovals: ['faculty', 'mentor', 'approvals'] as const,
  },
  hod: {
    dashboard: ['hod', 'dashboard'] as const,
    approvals: ['hod', 'approvals'] as const,
    facultyList: ['hod', 'faculty'] as const,
    studentList: ['hod', 'students'] as const,
    tasks: ['hod', 'tasks'] as const,
    circulars: ['hod', 'circulars'] as const,
    availability: ['hod', 'availability'] as const,
    reports: ['hod', 'reports'] as const,
  },
  principal: {
    dashboard: ['principal', 'dashboard'] as const,
    approvals: ['principal', 'approvals'] as const,
    delegation: ['principal', 'delegation'] as const,
    circulars: ['principal', 'circulars'] as const,
    reports: ['principal', 'reports'] as const,
  },
  vp: {
    dashboard: ['vp', 'dashboard'] as const,
    delegationQueue: ['vp', 'delegationQueue'] as const,
  },
  dean: {
    dashboard: ['dean', 'dashboard'] as const,
    approvals: ['dean', 'approvals'] as const,
  },
  common: {
    messages: ['messages'] as const,
    notifications: ['notifications'] as const,
    unreadCounts: ['unread-counts'] as const,
  },
};
