CREATE TABLE "fee_structures" ("id" TEXT PRIMARY KEY, "structureNumber" TEXT NOT NULL UNIQUE, "academicYearLabel" TEXT NOT NULL, "programId" TEXT, "departmentId" TEXT, "year" INTEGER, "semester" INTEGER, "categoryId" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "dueDate" DATE NOT NULL, "installmentOptions" TEXT, "lateFeeRules" TEXT, "status" TEXT NOT NULL DEFAULT 'DRAFT', "createdById" TEXT NOT NULL, "approvedById" TEXT, "approvedAt" TIMESTAMP(3), "activatedAt" TIMESTAMP(3), "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "fee_structures_academicYearLabel_status_idx" ON "fee_structures"("academicYearLabel", "status");
CREATE INDEX "fee_structures_departmentId_programId_idx" ON "fee_structures"("departmentId", "programId");

CREATE TABLE "finance_ledger_entries" ("id" TEXT PRIMARY KEY, "entryNumber" TEXT NOT NULL UNIQUE, "entryType" TEXT NOT NULL, "direction" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "currency" TEXT NOT NULL DEFAULT 'INR', "description" TEXT NOT NULL, "paymentId" TEXT, "billId" TEXT, "studentId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "sourceType" TEXT NOT NULL, "sourceId" TEXT NOT NULL, "metadataJson" TEXT, "postedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "finance_ledger_entries_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "fee_payments"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_ledger_entries_billId_fkey" FOREIGN KEY ("billId") REFERENCES "fee_bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_ledger_entries_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_ledger_entries_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "finance_ledger_entries_sourceType_sourceId_entryType_key" ON "finance_ledger_entries"("sourceType", "sourceId", "entryType");
CREATE INDEX "finance_ledger_entries_studentId_postedAt_idx" ON "finance_ledger_entries"("studentId", "postedAt"); CREATE INDEX "finance_ledger_entries_billId_postedAt_idx" ON "finance_ledger_entries"("billId", "postedAt"); CREATE INDEX "finance_ledger_entries_paymentId_idx" ON "finance_ledger_entries"("paymentId");

CREATE TABLE "daily_closings" ("id" TEXT PRIMARY KEY, "closingNumber" TEXT NOT NULL UNIQUE, "closingDate" DATE NOT NULL, "accountantId" TEXT NOT NULL, "expectedTotal" DOUBLE PRECISION NOT NULL, "actualTotal" DOUBLE PRECISION NOT NULL, "onlineTotal" DOUBLE PRECISION NOT NULL, "offlineTotal" DOUBLE PRECISION NOT NULL, "cashTotal" DOUBLE PRECISION NOT NULL, "upiTotal" DOUBLE PRECISION NOT NULL, "bankTotal" DOUBLE PRECISION NOT NULL, "chequeTotal" DOUBLE PRECISION NOT NULL, "ddTotal" DOUBLE PRECISION NOT NULL, "refundTotal" DOUBLE PRECISION NOT NULL, "adjustmentTotal" DOUBLE PRECISION NOT NULL, "difference" DOUBLE PRECISION NOT NULL, "cashCount" DOUBLE PRECISION, "remarks" TEXT, "supportUrl" TEXT, "snapshotJson" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "submittedAt" TIMESTAMP(3), "reviewedById" TEXT, "reviewedAt" TIMESTAMP(3), "returnReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "daily_closings_accountantId_fkey" FOREIGN KEY ("accountantId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "daily_closings_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "daily_closings_accountantId_closingDate_key" ON "daily_closings"("accountantId", "closingDate"); CREATE INDEX "daily_closings_status_closingDate_idx" ON "daily_closings"("status", "closingDate");
CREATE TABLE "daily_closing_approvals" ("id" TEXT PRIMARY KEY, "closingId" TEXT NOT NULL, "action" TEXT NOT NULL, "reason" TEXT, "actorId" TEXT NOT NULL, "beforeJson" TEXT, "afterJson" TEXT, "ipAddress" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "daily_closing_approvals_closingId_fkey" FOREIGN KEY ("closingId") REFERENCES "daily_closings"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "daily_closing_approvals_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE); CREATE INDEX "daily_closing_approvals_closingId_createdAt_idx" ON "daily_closing_approvals"("closingId", "createdAt");

CREATE TABLE "finance_requests" ("id" TEXT PRIMARY KEY, "requestNumber" TEXT NOT NULL UNIQUE, "requestType" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'REQUESTED', "amount" DOUBLE PRECISION NOT NULL, "originalAmount" DOUBLE PRECISION, "reason" TEXT NOT NULL, "remarks" TEXT, "supportUrl" TEXT, "metadataJson" TEXT, "studentId" TEXT, "billId" TEXT, "paymentId" TEXT, "requestedById" TEXT NOT NULL, "reviewedById" TEXT, "reviewedAt" TIMESTAMP(3), "decisionReason" TEXT, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "finance_requests_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_requests_billId_fkey" FOREIGN KEY ("billId") REFERENCES "fee_bills"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_requests_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "fee_payments"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_requests_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_requests_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE); CREATE INDEX "finance_requests_requestType_status_createdAt_idx" ON "finance_requests"("requestType", "status", "createdAt"); CREATE INDEX "finance_requests_studentId_createdAt_idx" ON "finance_requests"("studentId", "createdAt");

CREATE TABLE "finance_reconciliations" ("id" TEXT PRIMARY KEY, "caseNumber" TEXT NOT NULL UNIQUE, "paymentId" TEXT, "exceptionType" TEXT NOT NULL, "campusAmount" DOUBLE PRECISION, "gatewayAmount" DOUBLE PRECISION, "settlementAmount" DOUBLE PRECISION, "status" TEXT NOT NULL DEFAULT 'OPEN', "assignedToId" TEXT, "remarks" TEXT, "proofUrl" TEXT, "resolutionJson" TEXT, "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "finance_reconciliations_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "fee_payments"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "finance_reconciliations_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE); CREATE INDEX "finance_reconciliations_status_exceptionType_idx" ON "finance_reconciliations"("status", "exceptionType"); CREATE INDEX "finance_reconciliations_paymentId_idx" ON "finance_reconciliations"("paymentId");

CREATE TABLE "financial_audit_logs" ("id" TEXT PRIMARY KEY, "actorId" TEXT NOT NULL, "actorRole" TEXT NOT NULL, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT NOT NULL, "beforeJson" TEXT, "afterJson" TEXT, "ipAddress" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "financial_audit_logs_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE); CREATE INDEX "financial_audit_logs_resourceType_resourceId_createdAt_idx" ON "financial_audit_logs"("resourceType", "resourceId", "createdAt"); CREATE INDEX "financial_audit_logs_actorId_createdAt_idx" ON "financial_audit_logs"("actorId", "createdAt");
