import type { NavEntry, NavGroupConfig } from './navigation.types';

const accountantItems: Array<[string,string,string,string,'overview'|'management'|'insights'|'communication'|'account']> = [
  ['dashboard','Dashboard','LayoutDashboard','Finance collection overview','overview'],['fee-collection','Fee Collection','IndianRupee','Collect authorized student payments','management'],['student-search','Student Fee Search','Search','Search student fee accounts','management'],['online-payments','Online Payments','CreditCard','Verified gateway transactions','management'],['offline-payments','Offline Payments','Landmark','Cash, UPI and bank collections','management'],['pending-fees','Pending Fees','Clock3','Outstanding and overdue fees','management'],['receipts','Receipts','Receipt','Search and download receipts','management'],['transactions','Transactions','ArrowLeftRight','Complete payment transaction ledger','management'],['refund-requests','Refund Requests','Undo2','Create and monitor refund requests','management'],['scholarships','Scholarships / Concessions','BadgePercent','Create scholarship and concession requests','management'],['daily-collection','Daily Collection','CalendarCheck','Daily totals and closing submission','insights'],['reports','Reports','FileBarChart','Finance reports and exports','insights'],['reconciliation','Reconciliation','Scale','Investigate payment exceptions','insights'],['notifications','Notifications','Bell','Finance workflow notifications','communication'],['profile','Profile','UserRound','Accountant profile and security','account']
];
const aoItems: Array<[string,string,string,string,'overview'|'monitoring'|'management'|'insights'|'communication'|'account']> = [
  ['dashboard','Dashboard','LayoutDashboard','Executive finance control overview','overview'],['collection-overview','Collection Overview','BarChart3','Institution-wide collections','monitoring'],['accountant-monitoring','Accountant Monitoring','UsersRound','Monitor accountant activity and totals','monitoring'],['closing-approvals','Daily Closing Approvals','CalendarCheck','Approve or return daily closings','management'],['fee-structure','Fee Structure','ListChecks','Manage fee structure workflow','management'],['pending-fees','Pending Fees','Clock3','Institution outstanding fees','management'],['scholarships-concessions','Scholarships / Concessions','BadgePercent','Review concessions and scholarships','management'],['refund-approvals','Refund Approvals','Undo2','Review controlled refund requests','management'],['adjustments','Adjustments','SlidersHorizontal','Controlled financial adjustments','management'],['reconciliation','Reconciliation','Scale','Resolve gateway and settlement exceptions','insights'],['reports','Reports','FileBarChart','Institution finance reports','insights'],['audit-logs','Audit Logs','ScrollText','Immutable financial audit trail','insights'],['notifications','Notifications','Bell','Finance oversight notifications','communication'],['profile','Profile','UserRound','AO profile and security','account']
];
const ACCOUNTANT_FINANCE_ROUTES:NavEntry[]=accountantItems.map(([id,label,icon,description,group],order)=>({id:`accountant-${id}`,label,icon,description,path:`/accountant/${id}`,roles:['ACCOUNTS_STAFF','Accounts Staff','ACCOUNTANT'],group,mobilePlacement:order<4?'tab':'more',order:order+1}));
const AO_FINANCE_ROUTES:NavEntry[]=aoItems.map(([id,label,icon,description,group],order)=>({id:`ao-${id}`,label,icon,description,path:`/ao/${id}`,roles:['ACCOUNTS_OFFICER','Accounts Officer','AO'],group,mobilePlacement:order<4?'tab':'more',order:order+1}));

const examinationCellRoles = [
  'EXAMINATION_CELL',
  'Examination Cell',
  'COE',
  'CONTROLLER_OF_EXAMINATIONS',
  'Controller of Examinations',
  'Controller of Examination',
];
const EXAMINATION_CELL_ROUTES: NavEntry[] = [
  { id: 'coe-dashboard', label: 'Dashboard', description: 'Exam operations and publication readiness', icon: 'LayoutDashboard', path: '/coe/dashboard', roles: examinationCellRoles, group: 'overview', mobilePlacement: 'tab', order: 1 },
  { id: 'coe-exams', label: 'Exam management', description: 'Create examinations and manage exam terms', icon: 'NotebookTabs', path: '/coe/exams', roles: examinationCellRoles, group: 'management', mobilePlacement: 'tab', order: 1 },
  { id: 'coe-schedules', label: 'Schedules', description: 'Build, validate and publish exam schedules', icon: 'CalendarRange', path: '/coe/schedules', roles: examinationCellRoles, group: 'management', mobilePlacement: 'tab', order: 2 },
  { id: 'coe-halls', label: 'Hall & seat allocation', description: 'Assign rooms and publish student seats', icon: 'Armchair', path: '/coe/halls', roles: examinationCellRoles, group: 'management', mobilePlacement: 'more', order: 3 },
  { id: 'coe-invigilation', label: 'Invigilation', description: 'Assign and monitor invigilation duties', icon: 'UsersRound', path: '/coe/invigilation', roles: examinationCellRoles, group: 'management', mobilePlacement: 'more', order: 4 },
  { id: 'coe-marks', label: 'Marks & results', description: 'Enter marks and manage result publication', icon: 'ChartNoAxesColumnIncreasing', path: '/coe/marks-results', roles: examinationCellRoles, group: 'academics', mobilePlacement: 'tab', order: 1 },
  { id: 'coe-timetable', label: 'Master timetable', description: 'Manage the authoritative institutional timetable', icon: 'CalendarDays', path: '/coe/master-timetable', roles: examinationCellRoles, group: 'academics', mobilePlacement: 'more', order: 2 },
  { id: 'coe-notifications', label: 'Notifications', description: 'Exam alerts and workflow updates', icon: 'Bell', path: '/notifications', roles: examinationCellRoles, group: 'communication', mobilePlacement: 'more', order: 1, badgeKey: 'unreadNotifications' },
  { id: 'coe-profile', label: 'My profile', description: 'Examination Cell account and security', icon: 'UserRound', path: '/profile', roles: examinationCellRoles, group: 'account', mobilePlacement: 'more', order: 1 },
];

const superAdminRoles = ['SUPER_ADMIN', 'Super Admin'];
const SUPER_ADMIN_ROUTES: NavEntry[] = [
  { id: 'super-admin-dashboard', label: 'Control Centre', description: 'Institution configuration and live health', icon: 'LayoutDashboard', path: '/admin/dashboard', roles: superAdminRoles, group: 'overview', mobilePlacement: 'tab', order: 1 },
  { id: 'super-admin-users', label: 'All Users', description: 'Search and manage institution identities', icon: 'Users', path: '/admin/people', roles: superAdminRoles, group: 'management', mobilePlacement: 'tab', order: 1 },
  { id: 'super-admin-students', label: 'Students', description: 'Student identities and lifecycle', icon: 'GraduationCap', path: '/students', roles: superAdminRoles, group: 'management', mobilePlacement: 'more', order: 2 },
  { id: 'super-admin-institution', label: 'Institution', description: 'Institution profile and configuration', icon: 'Building2', path: '/institution', roles: superAdminRoles, group: 'academics', mobilePlacement: 'more', order: 1 },
  { id: 'super-admin-academics', label: 'Academic Structure', description: 'Programs, departments and academic periods', icon: 'Network', path: '/academics', roles: superAdminRoles, group: 'academics', mobilePlacement: 'more', order: 2 },
  { id: 'super-admin-masters', label: 'Master Lists', description: 'Governed institutional reference data', icon: 'Database', path: '/master-lists', roles: superAdminRoles, group: 'academics', mobilePlacement: 'more', order: 3 },
  { id: 'super-admin-iam', label: 'Roles & Permissions', description: 'RBAC, ABAC and user assignments', icon: 'ShieldCheck', path: '/admin/iam', roles: superAdminRoles, group: 'responsibilities', mobilePlacement: 'tab', order: 1 },
  { id: 'super-admin-workspaces', label: 'Workspaces', description: 'Role workspaces and data scopes', icon: 'Layers3', path: '/admin/rbac', roles: superAdminRoles, group: 'responsibilities', mobilePlacement: 'more', order: 2 },
  { id: 'super-admin-workflows', label: 'Workflow Monitor', description: 'Requests, routing and service levels', icon: 'Workflow', path: '/work-management', roles: superAdminRoles, group: 'requests', mobilePlacement: 'tab', order: 1 },
  { id: 'super-admin-approvals', label: 'Approval Centre', description: 'Institution approval queues', icon: 'FileCheck2', path: '/approval-center', roles: superAdminRoles, group: 'requests', mobilePlacement: 'more', order: 2 },
  { id: 'super-admin-governance', label: 'Governance Suite', description: 'Policies and administrative governance', icon: 'GitBranch', path: '/governance', roles: superAdminRoles, group: 'requests', mobilePlacement: 'more', order: 3 },
  { id: 'super-admin-notifications', label: 'Notifications', description: 'Administrative alerts and updates', icon: 'Bell', path: '/notifications', roles: superAdminRoles, group: 'communication', mobilePlacement: 'more', order: 1 },
  { id: 'super-admin-settings', label: 'System Settings', description: 'Modules, features and integrations', icon: 'Settings2', path: '/settings', roles: superAdminRoles, group: 'system', mobilePlacement: 'more', order: 1 },
  { id: 'super-admin-backups', label: 'Backup Centre', description: 'Backup status and recovery controls', icon: 'HardDriveDownload', path: '/backups', roles: superAdminRoles, group: 'system', mobilePlacement: 'more', order: 2 },
  { id: 'super-admin-security', label: 'Audit & Security', description: 'Security events and administration history', icon: 'ScrollText', path: '/security-logs', roles: superAdminRoles, group: 'system', mobilePlacement: 'more', order: 3 },
];

/*
  CAMPUSOS ROUTE REGISTRY
  
  Single source of truth for ALL navigation entries.
  Powers: Desktop sidebar, Mobile bottom nav, Mobile More page,
          Command search, Breadcrumbs, Notification deep links.
  
  Rules:
  - label: FULL text, no ellipsis, no truncation
  - description: max 60 chars, plain English
  - icon: Lucide icon name from icon-map.ts
  - roles: exact role name strings matching backend
  - order: controls sort within group (lower = higher)
*/

export const ROUTE_REGISTRY: NavEntry[] = [
  ...SUPER_ADMIN_ROUTES,
  ...ACCOUNTANT_FINANCE_ROUTES,
  ...AO_FINANCE_ROUTES,
  ...EXAMINATION_CELL_ROUTES,
  {id:'principal-finance-overview',label:'Finance Overview',icon:'IndianRupee',description:'Read-only institutional finance monitoring',path:'/principal/finance',roles:['PRINCIPAL','Principal'],group:'monitoring',mobilePlacement:'more',order:20},
  {id:'academic-dean-dashboard',label:'Dashboard',icon:'LayoutDashboard',description:'Academic governance and institutional KPIs',path:'/academic-dean/dashboard',roles:['ACADEMIC_DEAN','Academic Dean'],group:'overview',mobilePlacement:'tab',order:1},
  {id:'academic-dean-tasks',label:'Task Workspace',icon:'Layers3',description:'Assign and review department work',path:'/academic-dean/tasks',roles:['ACADEMIC_DEAN','Academic Dean'],group:'management',mobilePlacement:'tab',order:1},
  {id:'academic-dean-academics',label:'Academic Monitoring',icon:'Activity',description:'Monitor departments, curriculum and delivery',path:'/academic-dean/academics',roles:['ACADEMIC_DEAN','Academic Dean'],group:'monitoring',mobilePlacement:'more',order:1},
  {id:'academic-dean-availability',label:'Department Availability',icon:'Building2',description:'View department leadership availability',path:'/academic-dean/department-availability',roles:['ACADEMIC_DEAN','Academic Dean'],group:'monitoring',mobilePlacement:'more',order:2},
  {id:'academic-dean-circulars',label:'Circulars',icon:'Megaphone',description:'Publish and review academic circulars',path:'/academic-dean/circulars',roles:['ACADEMIC_DEAN','Academic Dean'],group:'communication',mobilePlacement:'more',order:1},
  {id:'academic-dean-reports',label:'Reports & Analytics',icon:'ChartNoAxesColumnIncreasing',description:'Review institutional academic reports',path:'/academic-dean/reports',roles:['ACADEMIC_DEAN','Academic Dean'],group:'insights',mobilePlacement:'tab',order:1},
  {id:'academic-dean-notifications',label:'Notifications',icon:'Bell',description:'Academic workflow notifications',path:'/academic-dean/notifications',roles:['ACADEMIC_DEAN','Academic Dean'],group:'communication',mobilePlacement:'more',order:2},
  // Academic Dean - add approvals tab
  {id:'academic-dean-approvals',label:'Approvals',icon:'CircleCheckBig',description:'Academic approval requests',path:'/academic-dean/approvals',roles:['ACADEMIC_DEAN','Academic Dean'],group:'overview',mobilePlacement:'tab',order:3,badgeKey:'pendingApprovals'},
  {id:'academic-dean-profile',label:'My Profile',icon:'UserRound',description:'View and edit your profile',path:'/academic-dean/profile',roles:['ACADEMIC_DEAN','Academic Dean'],group:'account',mobilePlacement:'more',order:1},

  // ADMISSION DEAN routes
  {id:'admission-dean-dashboard',label:'Dashboard',icon:'LayoutDashboard',description:'Admissions and administration overview',path:'/admission-dean/dashboard',roles:['ADMISSION_DEAN','Admission Dean','ADMISSION_AND_ADMINISTRATION_DEAN','ADMINISTRATION_DEAN'],group:'overview',mobilePlacement:'tab',order:1},
  {id:'admission-dean-admissions',label:'Admissions',icon:'UserPlus',description:'Applications and admission funnel',path:'/admission-dean/admissions',roles:['ADMISSION_DEAN','Admission Dean','ADMISSION_AND_ADMINISTRATION_DEAN','ADMINISTRATION_DEAN'],group:'management',mobilePlacement:'tab',order:1},
  {id:'admission-dean-services',label:'Student Services',icon:'Layers3',description:'Student administration & services',path:'/admission-dean/services',roles:['ADMISSION_DEAN','Admission Dean','ADMISSION_AND_ADMINISTRATION_DEAN','ADMINISTRATION_DEAN'],group:'management',mobilePlacement:'tab',order:2},
  {id:'admission-dean-approvals',label:'Requests & Approvals',icon:'CircleCheckBig',description:'Administrative and admission requests',path:'/admission-dean/approvals',roles:['ADMISSION_DEAN','Admission Dean','ADMISSION_AND_ADMINISTRATION_DEAN','ADMINISTRATION_DEAN'],group:'requests',mobilePlacement:'tab',order:1,badgeKey:'pendingApprovals'},
  {id:'admission-dean-notifications',label:'Notifications',icon:'Bell',description:'Admission alerts and updates',path:'/admission-dean/notifications',roles:['ADMISSION_DEAN','Admission Dean','ADMISSION_AND_ADMINISTRATION_DEAN','ADMINISTRATION_DEAN'],group:'communication',mobilePlacement:'more',order:1},
  {id:'admission-dean-profile',label:'My Profile',icon:'UserRound',description:'View and edit your profile',path:'/admission-dean/profile',roles:['ADMISSION_DEAN','Admission Dean','ADMISSION_AND_ADMINISTRATION_DEAN','ADMINISTRATION_DEAN'],group:'account',mobilePlacement:'more',order:1},

  // IQAC routes
  {id:'iqac-dashboard',label:'Dashboard',icon:'LayoutDashboard',description:'Quality overview and accreditation KPIs',path:'/iqac/dashboard',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'overview',mobilePlacement:'tab',order:1},
  {id:'iqac-approvals',label:'Approvals',icon:'CircleCheckBig',description:'IQAC approval requests',path:'/iqac/approvals',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'overview',mobilePlacement:'tab',order:2,badgeKey:'pendingApprovals'},
  {id:'iqac-evidence',label:'Evidence',icon:'FolderArchive',description:'Quality evidence repository',path:'/iqac/evidence',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'management',mobilePlacement:'tab',order:1},
  {id:'iqac-tasks',label:'Tasks',icon:'ListChecks',description:'Accreditation tasks and deadlines',path:'/iqac/tasks',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'management',mobilePlacement:'more',order:2,badgeKey:'pendingTasks'},
  {id:'iqac-accreditation',label:'Accreditation',icon:'Award',description:'NAAC, NBA and accreditation workflows',path:'/iqac/accreditation',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'management',mobilePlacement:'more',order:3},
  {id:'iqac-reports',label:'Reports',icon:'ChartSpline',description:'Quality and accreditation reports',path:'/iqac/reports',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'insights',mobilePlacement:'more',order:1},
  {id:'iqac-circulars',label:'Circulars',icon:'Megaphone',description:'Quality circulars and notices',path:'/iqac/circulars',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'communication',mobilePlacement:'more',order:1},
  {id:'iqac-notifications',label:'Notifications',icon:'Bell',description:'Quality workflow notifications',path:'/iqac/notifications',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'communication',mobilePlacement:'tab',order:4,badgeKey:'unreadNotifications'},
  {id:'iqac-profile',label:'My Profile',icon:'UserRound',description:'View and edit your profile',path:'/iqac/profile',roles:['IQAC','IQAC_DEAN','IQAC Dean'],group:'account',mobilePlacement:'more',order:1},

  // MENTOR routes (faculty acting as mentor)
  {id:'mentor-dashboard',label:'Dashboard',icon:'LayoutDashboard',description:'Mentor overview and mentee status',path:'/faculty/mentor/dashboard',roles:['MENTOR'],group:'overview',mobilePlacement:'tab',order:1},
  {id:'mentor-students',label:'My Mentees',icon:'Heart',description:'All your assigned mentee students',path:'/mentor/students',roles:['MENTOR'],group:'teaching',mobilePlacement:'tab',order:1},
  {id:'mentor-leave-od',label:'Approvals',icon:'CircleCheckBig',description:'Leave and OD approval requests from mentees',path:'/mentor/leave-od',roles:['MENTOR'],group:'requests',mobilePlacement:'tab',order:1,badgeKey:'pendingApprovals'},
  {id:'mentor-attendance',label:'Attendance',icon:'ClipboardCheck',description:'Mentee attendance overview',path:'/faculty/mentor/attendance',roles:['MENTOR'],group:'academics',mobilePlacement:'more',order:1},
  {id:'mentor-academics',label:'Academic Performance',icon:'ChartNoAxesColumnIncreasing',description:'Mentee academic progress',path:'/faculty/mentor/academics',roles:['MENTOR'],group:'academics',mobilePlacement:'more',order:2},
  {id:'mentor-counselling',label:'Counselling',icon:'MessageSquare',description:'Counselling sessions and notes',path:'/faculty/mentor/counselling',roles:['MENTOR'],group:'responsibilities',mobilePlacement:'more',order:1},
  {id:'mentor-parents',label:'Parent Comm',icon:'Phone',description:'Parent communication and meetings',path:'/faculty/mentor/parents',roles:['MENTOR'],group:'responsibilities',mobilePlacement:'more',order:2},
  {id:'mentor-notifications',label:'Notifications',icon:'Bell',description:'Mentor notifications',path:'/faculty/notifications',roles:['MENTOR'],group:'communication',mobilePlacement:'more',order:1,badgeKey:'unreadNotifications'},
  {id:'mentor-profile',label:'My Profile',icon:'UserRound',description:'View and edit your profile',path:'/faculty/profile',roles:['MENTOR'],group:'account',mobilePlacement:'more',order:4},

  // CLASS_ADVISER routes
  {id:'class-adviser-dashboard',label:'Dashboard',icon:'LayoutDashboard',description:'Class overview and student status',path:'/class-adviser/dashboard',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'overview',mobilePlacement:'tab',order:1},
  {id:'class-adviser-students',label:'My Class',icon:'GraduationCap',description:'Students in your assigned class',path:'/class-adviser/students',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'teaching',mobilePlacement:'tab',order:1},
  {id:'class-adviser-attendance',label:'Attendance',icon:'ClipboardCheck',description:'Class attendance monitoring',path:'/class-adviser/attendance',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'teaching',mobilePlacement:'tab',order:2},
  {id:'class-adviser-approvals',label:'Approvals',icon:'CircleCheckBig',description:'Class student leave and requests',path:'/class-adviser/leave-od',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'requests',mobilePlacement:'tab',order:1,badgeKey:'pendingApprovals'},
  {id:'class-adviser-academics',label:'Academic Progress',icon:'ChartNoAxesColumnIncreasing',description:'Academic performance of class',path:'/class-adviser/academics',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'academics',mobilePlacement:'more',order:1},
  {id:'class-adviser-circulars',label:'Circulars',icon:'Megaphone',description:'Class circulars and notices',path:'/class-adviser/circulars',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'communication',mobilePlacement:'more',order:1},
  {id:'class-adviser-notifications',label:'Notifications',icon:'Bell',description:'Class advisement alerts',path:'/class-adviser/notifications',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'communication',mobilePlacement:'more',order:2},
  {id:'class-adviser-profile',label:'My Profile',icon:'UserRound',description:'View and edit your profile',path:'/class-adviser/profile',roles:['CLASS_ADVISER','Class Adviser','CLASS_ADVISOR'],group:'account',mobilePlacement:'tab',order:4},

  // Notification and sub-tab routes
  {id:'student-notifications',label:'Notifications',icon:'Bell',description:'Student alerts and updates',path:'/student/notifications',roles:['STUDENT','student'],group:'communication',mobilePlacement:'tab',order:3,badgeKey:'unreadNotifications'},
  {id:'faculty-notifications',label:'Notifications',icon:'Bell',description:'Faculty alerts and notices',path:'/faculty/notifications',roles:['FACULTY','faculty','FACULTY_MEMBER'],group:'communication',mobilePlacement:'tab',order:4,badgeKey:'unreadNotifications'},
  {id:'hod-department-overview',label:'Department',icon:'Building2',description:'Department profile and structure',path:'/hod/department-overview',roles:['HOD','HEAD_OF_DEPARTMENT'],group:'management',mobilePlacement:'tab',order:2},
  {id:'hod-notifications',label:'Notifications',icon:'Bell',description:'Department notifications',path:'/hod/notifications',roles:['HOD','HEAD_OF_DEPARTMENT'],group:'communication',mobilePlacement:'tab',order:4,badgeKey:'unreadNotifications'},
  {id:'principal-notifications',label:'Notifications',icon:'Bell',description:'Executive alerts and notices',path:'/principal/notifications',roles:['PRINCIPAL','Principal'],group:'communication',mobilePlacement:'tab',order:4,badgeKey:'unreadNotifications'},

  // ====================================================
  // STUDENT ROUTES
  // ====================================================
  {
    id: 'student-dashboard',
    label: 'Dashboard',
    description: 'Your daily overview and quick actions',
    icon: 'LayoutDashboard',
    path: '/student/dashboard',
    roles: ['STUDENT', 'student'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'student-timetable',
    label: 'Timetable',
    description: 'View your class schedule and upcoming sessions',
    icon: 'CalendarDays',
    path: '/student/timetable',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'timetableUpdates',
  },
  {
    id: 'student-attendance',
    label: 'Attendance',
    description: 'Check your attendance and shortage alerts',
    icon: 'ClipboardCheck',
    path: '/student/attendance',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'student-assignments',
    label: 'Assignments',
    description: 'View pending and submitted assignments',
    icon: 'FileText',
    path: '/student/assignments',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 4,
    badgeKey: 'pendingAssignments',
  },
  {
    id: 'student-marks',
    label: 'Marks & Results',
    description: 'Internal marks and exam results',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/student/results',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 5,
  },
  {
    id: 'student-examinations',
    label: 'Examinations',
    description: 'Exam schedule, hall ticket and results',
    icon: 'NotebookTabs',
    path: '/student/examinations',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 6,
  },
  {
    id: 'student-leave-od',
    label: 'Leave & OD Requests',
    shortLabel: 'Requests',
    description: 'Apply for leave or on-duty and check status',
    icon: 'CalendarOff',
    path: '/student/leave-od',
    roles: ['STUDENT', 'student'],
    group: 'requests',
    mobilePlacement: 'tab',
    order: 1,
    badgeKey: 'pendingLeaveRequests',
  },
  {
    id: 'student-fees',
    label: 'Fees & Payments',
    description: 'Pay fees and download receipts',
    icon: 'IndianRupee',
    path: '/student/fees',
    roles: ['STUDENT', 'student'],
    group: 'requests',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'student-circulars',
    label: 'Circulars',
    description: 'College announcements and notices',
    icon: 'Megaphone',
    path: '/student/circulars',
    roles: ['STUDENT', 'student'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
    badgeKey: 'unreadCirculars',
  },
  {
    id: 'student-messages',
    label: 'Messages',
    description: 'Messages from your mentor and faculty',
    icon: 'MessageSquare',
    path: '/student/messages',
    roles: ['STUDENT', 'student'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'unreadMessages',
  },
  {
    id: 'student-placements',
    label: 'Placement Opportunities',
    description: 'Campus placements and job opportunities',
    icon: 'BriefcaseBusiness',
    path: '/student/placements',
    roles: ['STUDENT', 'student'],
    group: 'career',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'student-documents',
    label: 'My Certificates',
    description: 'Request and download certificates',
    icon: 'FileText',
    path: '/student/certificates',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'student-complaints',
    label: 'Grievances',
    description: 'File a complaint and track its resolution',
    icon: 'MessageSquare',
    path: '/student/complaints',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'student-idcard',
    label: 'Digital ID Card',
    description: 'Your digital student identity card',
    icon: 'CreditCard',
    path: '/student/id-card',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'student-achievements',
    label: 'Achievements',
    description: 'Verified accomplishments and campus showcase',
    icon: 'Sparkles',
    path: '/student/achievements',
    roles: ['STUDENT', 'student'],
    group: 'career',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'student-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/student/profile',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 3,
  },

  // ====================================================
  // FACULTY ROUTES
  // ====================================================
  {
    id: 'faculty-dashboard',
    label: 'Dashboard',
    description: 'Your teaching overview and daily priorities',
    icon: 'LayoutDashboard',
    path: '/faculty/dashboard',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'faculty-timetable',
    label: 'Timetable',
    description: 'Your teaching schedule for the week',
    icon: 'CalendarDays',
    path: '/faculty/timetable',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'faculty-attendance',
    label: 'Mark Attendance',
    description: 'Mark and manage student attendance',
    icon: 'ClipboardCheck',
    path: '/faculty/attendance',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'faculty-assignments',
    label: 'Assignments',
    description: 'Create and grade student assignments',
    icon: 'FileText',
    path: '/faculty/assignments',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'faculty-marks',
    label: 'Internal Marks',
    description: 'Enter and publish student marks',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/faculty/internal-marks',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'faculty-students',
    label: 'My Students',
    description: 'View students in your assigned subjects',
    icon: 'GraduationCap',
    path: '/faculty/students',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'more',
    order: 5,
  },
  {
    id: 'faculty-mentor-dashboard',
    label: 'Mentor Workspace',
    description: 'Manage your mentee students',
    icon: 'Heart',
    path: '/faculty/mentor/dashboard',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'responsibilities',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'faculty-leave-od',
    label: 'My Leave & OD',
    description: 'Apply for leave or on-duty requests',
    icon: 'CalendarOff',
    path: '/faculty/leave-od',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'responsibilities',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'faculty-tasks',
    label: 'Tasks',
    description: 'Assigned tasks and their deadlines',
    icon: 'ListChecks',
    path: '/faculty/tasks',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'responsibilities',
    mobilePlacement: 'tab',
    order: 3,
    badgeKey: 'pendingTasks',
  },
  {
    id: 'faculty-circulars',
    label: 'Circulars',
    description: 'College announcements for faculty',
    icon: 'Megaphone',
    path: '/faculty/circulars',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
    badgeKey: 'unreadCirculars',
  },
  {
    id: 'faculty-reports',
    label: 'Subject Reports',
    description: 'Attendance and performance reports',
    icon: 'ChartSpline',
    path: '/faculty/reports',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'faculty-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/faculty/profile',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 1,
  },

  // ====================================================
  // HOD ROUTES
  // ====================================================
  {
    id: 'hod-dashboard',
    label: 'Dashboard',
    description: 'Department overview and daily priorities',
    icon: 'LayoutDashboard',
    path: '/hod/dashboard',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'hod-approvals',
    label: 'Pending Approvals',
    description: 'Leave, OD and request approvals',
    icon: 'CircleCheckBig',
    path: '/hod/approvals',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'pendingApprovals',
  },
  {
    id: 'hod-availability',
    label: 'Availability Board',
    description: 'Live faculty and student availability',
    icon: 'RadioTower',
    path: '/hod/department-availability',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'hod-faculty',
    label: 'Faculty Directory',
    description: 'All faculty in your department',
    icon: 'Users',
    path: '/hod/faculty',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'hod-allocation',
    label: 'Faculty Allocation',
    description: 'Assign faculty to subjects and sections',
    icon: 'Layers3',
    path: '/hod/allocation',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'hod-students',
    label: 'Student Records',
    description: 'All students in your department',
    icon: 'GraduationCap',
    path: '/hod/students',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'hod-mentors',
    label: 'Mentor Assignments',
    description: 'Student-mentor mapping in your department',
    icon: 'Heart',
    path: '/hod/mentors',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'hod-tasks',
    label: 'Department Tasks',
    description: 'Tasks assigned to the department',
    icon: 'ListChecks',
    path: '/hod/tasks',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 5,
    badgeKey: 'pendingTasks',
  },
  {
    id: 'hod-circulars',
    label: 'Circulars',
    description: 'Publish and view department circulars',
    icon: 'Megaphone',
    path: '/hod/circulars',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'hod-complaints',
    label: 'Complaints',
    description: 'Student and faculty complaints',
    icon: 'MessageCircleWarning',
    path: '/hod/complaints',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'hod-academics',
    label: 'Academic Performance',
    description: 'Department attendance and marks overview',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/hod/academics',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'hod-reports',
    label: 'Department Reports',
    description: 'Generate and export department reports',
    icon: 'ChartSpline',
    path: '/hod/reports',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'hod-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/hod/profile',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'account',
    mobilePlacement: 'more',
    order: 1,
  },

  // ====================================================
  // PRINCIPAL ROUTES
  // ====================================================
  {
    id: 'principal-dashboard',
    label: 'Executive Dashboard',
    shortLabel: 'Home',
    description: 'Institution overview and daily priorities',
    icon: 'LayoutDashboard',
    path: '/principal/dashboard',
    roles: ['PRINCIPAL'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'principal-approvals',
    label: 'Approval Center',
    shortLabel: 'Approvals',
    description: 'All pending approvals across the institution',
    icon: 'CircleCheckBig',
    path: '/principal/approval-center',
    roles: ['PRINCIPAL'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'pendingApprovals',
  },
  {
    id: 'principal-availability',
    label: 'Campus Availability',
    description: 'Live attendance and availability board',
    icon: 'RadioTower',
    path: '/principal/department-availability',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'principal-departments',
    label: 'Departments',
    description: 'All departments and their performance',
    icon: 'Building2',
    path: '/principal/departments',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'principal-faculty',
    label: 'Faculty Directory',
    description: 'All faculty members in the institution',
    icon: 'Users',
    path: '/principal/faculty',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'principal-students',
    label: 'Student Directory',
    description: 'All students in the institution',
    icon: 'GraduationCap',
    path: '/principal/students',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'principal-tasks',
    label: 'Tasks',
    description: 'Institution-wide task assignments',
    icon: 'ListChecks',
    path: '/principal/tasks',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
    badgeKey: 'pendingTasks',
  },
  {
    id: 'principal-circulars',
    label: 'Circulars',
    description: 'Publish and manage circulars',
    icon: 'Megaphone',
    path: '/principal/circulars',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'principal-complaints',
    label: 'Complaints',
    description: 'All complaints requiring attention',
    icon: 'MessageCircleWarning',
    path: '/principal/complaints',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'principal-reports',
    label: 'Institution Reports',
    shortLabel: 'Reports',
    description: 'Institution-wide analytics and exports',
    icon: 'ChartSpline',
    path: '/principal/reports',
    roles: ['PRINCIPAL'],
    group: 'insights',
    mobilePlacement: 'tab',
    order: 3,
  },
  {
    id: 'principal-placement',
    label: 'Placement Summary',
    description: 'Placement statistics and recent results',
    icon: 'BriefcaseBusiness',
    path: '/principal/placement',
    roles: ['PRINCIPAL'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'principal-delegation',
    label: 'Principal Delegation',
    description: 'Manage availability and delegate to VP',
    icon: 'UserRoundCog',
    path: '/principal/delegation',
    roles: ['PRINCIPAL'],
    group: 'account',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'principal-search',
    label: 'Search Campus',
    shortLabel: 'Search',
    description: 'Search students, faculty and records',
    icon: 'Search',
    path: '/principal/search',
    roles: ['PRINCIPAL'],
    group: 'overview',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'principal-profile',
    label: 'My Profile',
    shortLabel: 'Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/principal/profile',
    roles: ['PRINCIPAL'],
    group: 'account',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'principal-notifications',
    label: 'Notifications',
    shortLabel: 'Alerts',
    description: 'Principal notifications and alerts',
    icon: 'Bell',
    path: '/principal/notifications',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 4,
    badgeKey: 'unreadNotifications',
  },

  // ====================================================
  // VICE PRINCIPAL ROUTES
  // ====================================================
  {
    id: 'vp-dashboard',
    label: 'VP Operations',
    description: 'Operations overview and delegated approvals',
    icon: 'LayoutDashboard',
    path: '/vp/dashboard',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'vp-leave-approvals',
    label: 'Approvals & Workflows',
    description: 'Executive approvals and request workflows',
    icon: 'CircleCheckBig',
    path: '/vp/leave-approvals',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'pendingApprovals',
  },
  {
    id: 'vp-availability',
    label: 'Availability Board',
    description: 'Live campus availability',
    icon: 'RadioTower',
    path: '/vp/department-availability',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'management',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'vp-departments',
    label: 'Departments',
    description: 'Monitor department performance',
    icon: 'Building2',
    path: '/vp/departments',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'management',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'vp-placement',
    label: 'Placement Overview',
    description: 'Track placement and internship activities',
    icon: 'BriefcaseBusiness',
    path: '/vp/placements',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'vp-reports',
    label: 'Operations Reports',
    description: 'Institution-wide operations analytics',
    icon: 'ChartSpline',
    path: '/vp/reports',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'vp-circulars',
    label: 'Circulars',
    description: 'View and manage circulars',
    icon: 'Megaphone',
    path: '/vp/circulars',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'vp-notifications',
    label: 'Alerts',
    description: 'Important alerts and notifications',
    icon: 'Bell',
    path: '/vp/notifications',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 4,
    badgeKey: 'unreadNotifications',
  },
  {
    id: 'vp-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/vp/profile',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'account',
    mobilePlacement: 'more',
    order: 5,
  },

  // ====================================================
  // PARENT ROUTES
  // ====================================================
  {
    id: 'parent-dashboard',
    label: "Child's Dashboard",
    description: "Overview of your child's academic status",
    icon: 'LayoutDashboard',
    path: '/parent/dashboard',
    roles: ['PARENT', 'parent'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'parent-attendance',
    label: 'Attendance',
    description: "Track your child's daily attendance",
    icon: 'ClipboardCheck',
    path: '/parent/attendance',
    roles: ['PARENT', 'parent'],
    group: 'academics',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'parent-marks',
    label: 'Academic Performance',
    description: 'View marks, results and performance trends',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/parent/marks',
    roles: ['PARENT', 'parent'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'parent-timetable',
    label: 'Timetable',
    description: "Your child's class schedule",
    icon: 'CalendarDays',
    path: '/parent/timetable',
    roles: ['PARENT', 'parent'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'parent-fees',
    label: 'Fees & Payments',
    description: 'Pay fees and download receipts',
    icon: 'IndianRupee',
    path: '/parent/fees',
    roles: ['PARENT', 'parent'],
    group: 'requests',
    mobilePlacement: 'tab',
    order: 1,
    badgeKey: 'pendingFees',
  },
  {
    id: 'parent-messages',
    label: 'Messages',
    description: 'Messages from the mentor and college',
    icon: 'MessageSquare',
    path: '/parent/messages',
    roles: ['PARENT', 'parent'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 1,
    badgeKey: 'unreadMessages',
  },
  {
    id: 'parent-circulars',
    label: 'Circulars',
    description: 'College announcements and important notices',
    icon: 'Megaphone',
    path: '/parent/circulars',
    roles: ['PARENT', 'parent'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'parent-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/parent/profile',
    roles: ['PARENT', 'parent'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 1,
  },
];

// Sidebar group labels per role display name
export const NAV_GROUP_CONFIGS: NavGroupConfig[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'monitoring', label: 'Monitoring' },
  { id: 'teaching', label: 'Teaching' },
  { id: 'academics', label: 'Academics' },
  { id: 'communication', label: 'Communication' },
  { id: 'management', label: 'Management' },
  { id: 'requests', label: 'Requests & Finance' },
  { id: 'responsibilities', label: 'Responsibilities' },
  { id: 'insights', label: 'Insights' },
  { id: 'career', label: 'Career' },
  { id: 'account', label: 'Account' },
  { id: 'system', label: 'System' },
];
