import type { NavEntry, NavGroupConfig } from './navigation.types';

/*
  CAMPUSOS ROUTE REGISTRY
  
  Single source of truth for ALL navigation entries.
  Powers: Desktop sidebar, Mobile bottom nav, Mobile More page,
          Command search, Breadcrumbs, Notification deep links.
  
  Rules:
  - label: FULL text, no ellipsis, no truncation
  - description: max 60 chars, plain English
  - icon: Lucide icon name from icon-map.ts
  - roles: exact role name strings matching backend
  - order: controls sort within group (lower = higher)
*/

export const ROUTE_REGISTRY: NavEntry[] = [
  // ====================================================
  // STUDENT ROUTES
  // ====================================================
  {
    id: 'student-dashboard',
    label: 'Dashboard',
    description: 'Your daily overview and quick actions',
    icon: 'LayoutDashboard',
    path: '/student/dashboard',
    roles: ['STUDENT', 'student'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'student-timetable',
    label: 'Timetable',
    description: 'View your class schedule and upcoming sessions',
    icon: 'CalendarDays',
    path: '/student/timetable',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'timetableUpdates',
  },
  {
    id: 'student-attendance',
    label: 'Attendance',
    description: 'Check your attendance and shortage alerts',
    icon: 'ClipboardCheck',
    path: '/student/attendance',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'student-assignments',
    label: 'Assignments',
    description: 'View pending and submitted assignments',
    icon: 'FileText',
    path: '/student/assignments',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 4,
    badgeKey: 'pendingAssignments',
  },
  {
    id: 'student-marks',
    label: 'Marks & Results',
    description: 'Internal marks and exam results',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/student/results',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 5,
  },
  {
    id: 'student-examinations',
    label: 'Examinations',
    description: 'Exam schedule, hall ticket and results',
    icon: 'NotebookTabs',
    path: '/student/examinations',
    roles: ['STUDENT', 'student'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 6,
  },
  {
    id: 'student-leave-od',
    label: 'Leave & OD Requests',
    shortLabel: 'Requests',
    description: 'Apply for leave or on-duty and check status',
    icon: 'CalendarOff',
    path: '/student/leave-od',
    roles: ['STUDENT', 'student'],
    group: 'requests',
    mobilePlacement: 'tab',
    order: 1,
    badgeKey: 'pendingLeaveRequests',
  },
  {
    id: 'student-fees',
    label: 'Fees & Payments',
    description: 'Pay fees and download receipts',
    icon: 'IndianRupee',
    path: '/student/fees',
    roles: ['STUDENT', 'student'],
    group: 'requests',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'student-circulars',
    label: 'Circulars',
    description: 'College announcements and notices',
    icon: 'Megaphone',
    path: '/student/circulars',
    roles: ['STUDENT', 'student'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
    badgeKey: 'unreadCirculars',
  },
  {
    id: 'student-messages',
    label: 'Messages',
    description: 'Messages from your mentor and faculty',
    icon: 'MessageSquare',
    path: '/student/messages',
    roles: ['STUDENT', 'student'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'unreadMessages',
  },
  {
    id: 'student-placements',
    label: 'Placement Opportunities',
    description: 'Campus placements and job opportunities',
    icon: 'BriefcaseBusiness',
    path: '/student/placements',
    roles: ['STUDENT', 'student'],
    group: 'career',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'student-documents',
    label: 'My Documents',
    description: 'Download certificates and transcripts',
    icon: 'FileText',
    path: '/student/documents',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'student-idcard',
    label: 'Digital ID Card',
    description: 'Your digital student identity card',
    icon: 'CreditCard',
    path: '/student/id-card',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'student-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/student/profile',
    roles: ['STUDENT', 'student'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 3,
  },

  // ====================================================
  // FACULTY ROUTES
  // ====================================================
  {
    id: 'faculty-dashboard',
    label: 'Dashboard',
    description: 'Your teaching overview and daily priorities',
    icon: 'LayoutDashboard',
    path: '/faculty/dashboard',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'faculty-timetable',
    label: 'Timetable',
    description: 'Your teaching schedule for the week',
    icon: 'CalendarDays',
    path: '/faculty/timetable',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'faculty-attendance',
    label: 'Mark Attendance',
    description: 'Mark and manage student attendance',
    icon: 'ClipboardCheck',
    path: '/faculty/attendance',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'tab',
    order: 2,
  },
  {
    id: 'faculty-assignments',
    label: 'Assignments',
    description: 'Create and grade student assignments',
    icon: 'FileText',
    path: '/faculty/assignments',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'faculty-marks',
    label: 'Internal Marks',
    description: 'Enter and publish student marks',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/faculty/internal-marks',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'faculty-students',
    label: 'My Students',
    description: 'View students in your assigned subjects',
    icon: 'GraduationCap',
    path: '/faculty/students',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'teaching',
    mobilePlacement: 'tab',
    order: 5,
  },
  {
    id: 'faculty-mentor-dashboard',
    label: 'Mentor Workspace',
    description: 'Manage your mentee students',
    icon: 'Heart',
    path: '/faculty/mentor/dashboard',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'responsibilities',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'faculty-leave-od',
    label: 'My Leave & OD',
    description: 'Apply for leave or on-duty requests',
    icon: 'CalendarOff',
    path: '/faculty/leave-od',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'responsibilities',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'faculty-tasks',
    label: 'Tasks',
    description: 'Assigned tasks and their deadlines',
    icon: 'ListChecks',
    path: '/faculty/tasks',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'responsibilities',
    mobilePlacement: 'tab',
    order: 3,
    badgeKey: 'pendingTasks',
  },
  {
    id: 'faculty-circulars',
    label: 'Circulars',
    description: 'College announcements for faculty',
    icon: 'Megaphone',
    path: '/faculty/circulars',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
    badgeKey: 'unreadCirculars',
  },
  {
    id: 'faculty-reports',
    label: 'Subject Reports',
    description: 'Attendance and performance reports',
    icon: 'ChartSpline',
    path: '/faculty/reports',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'faculty-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/faculty/profile',
    roles: ['FACULTY', 'faculty', 'FACULTY_MEMBER'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 1,
  },

  // ====================================================
  // HOD ROUTES
  // ====================================================
  {
    id: 'hod-dashboard',
    label: 'Dashboard',
    description: 'Department overview and daily priorities',
    icon: 'LayoutDashboard',
    path: '/hod/dashboard',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'hod-approvals',
    label: 'Pending Approvals',
    description: 'Leave, OD and request approvals',
    icon: 'CircleCheckBig',
    path: '/hod/approvals',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'pendingApprovals',
  },
  {
    id: 'hod-availability',
    label: 'Availability Board',
    description: 'Live faculty and student availability',
    icon: 'RadioTower',
    path: '/hod/department-availability',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'hod-faculty',
    label: 'Faculty Directory',
    description: 'All faculty in your department',
    icon: 'Users',
    path: '/hod/faculty',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'hod-students',
    label: 'Student Records',
    description: 'All students in your department',
    icon: 'GraduationCap',
    path: '/hod/students',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'hod-mentors',
    label: 'Mentor Assignments',
    description: 'Student-mentor mapping in your department',
    icon: 'Heart',
    path: '/hod/mentors',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'hod-tasks',
    label: 'Department Tasks',
    description: 'Tasks assigned to the department',
    icon: 'ListChecks',
    path: '/hod/tasks',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'management',
    mobilePlacement: 'tab',
    order: 5,
    badgeKey: 'pendingTasks',
  },
  {
    id: 'hod-circulars',
    label: 'Circulars',
    description: 'Publish and view department circulars',
    icon: 'Megaphone',
    path: '/hod/circulars',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'hod-complaints',
    label: 'Complaints',
    description: 'Student and faculty complaints',
    icon: 'MessageCircleWarning',
    path: '/hod/complaints',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'hod-academics',
    label: 'Academic Performance',
    description: 'Department attendance and marks overview',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/hod/academics',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'hod-reports',
    label: 'Department Reports',
    description: 'Generate and export department reports',
    icon: 'ChartSpline',
    path: '/hod/reports',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'hod-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/hod/profile',
    roles: ['HOD', 'HEAD_OF_DEPARTMENT'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 1,
  },

  // ====================================================
  // PRINCIPAL ROUTES
  // ====================================================
  {
    id: 'principal-dashboard',
    label: 'Executive Dashboard',
    shortLabel: 'Home',
    description: 'Institution overview and daily priorities',
    icon: 'LayoutDashboard',
    path: '/principal/dashboard',
    roles: ['PRINCIPAL'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'principal-approvals',
    label: 'Approval Center',
    shortLabel: 'Approvals',
    description: 'All pending approvals across the institution',
    icon: 'CircleCheckBig',
    path: '/principal/approval-center',
    roles: ['PRINCIPAL'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'pendingApprovals',
  },
  {
    id: 'principal-availability',
    label: 'Campus Availability',
    description: 'Live attendance and availability board',
    icon: 'RadioTower',
    path: '/principal/department-availability',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'principal-departments',
    label: 'Departments',
    description: 'All departments and their performance',
    icon: 'Building2',
    path: '/principal/departments',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'principal-faculty',
    label: 'Faculty Directory',
    description: 'All faculty members in the institution',
    icon: 'Users',
    path: '/principal/faculty',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'principal-students',
    label: 'Student Directory',
    description: 'All students in the institution',
    icon: 'GraduationCap',
    path: '/principal/students',
    roles: ['PRINCIPAL'],
    group: 'monitoring',
    mobilePlacement: 'more',
    order: 4,
  },
  {
    id: 'principal-tasks',
    label: 'Tasks',
    description: 'Institution-wide task assignments',
    icon: 'ListChecks',
    path: '/principal/tasks',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
    badgeKey: 'pendingTasks',
  },
  {
    id: 'principal-circulars',
    label: 'Circulars',
    description: 'Publish and manage circulars',
    icon: 'Megaphone',
    path: '/principal/circulars',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'principal-complaints',
    label: 'Complaints',
    description: 'All complaints requiring attention',
    icon: 'MessageCircleWarning',
    path: '/principal/complaints',
    roles: ['PRINCIPAL'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'principal-reports',
    label: 'Institution Reports',
    shortLabel: 'Reports',
    description: 'Institution-wide analytics and exports',
    icon: 'ChartSpline',
    path: '/principal/reports',
    roles: ['PRINCIPAL'],
    group: 'insights',
    mobilePlacement: 'tab',
    order: 3,
  },
  {
    id: 'principal-placement',
    label: 'Placement Summary',
    description: 'Placement statistics and recent results',
    icon: 'BriefcaseBusiness',
    path: '/principal/placement',
    roles: ['PRINCIPAL'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'principal-delegation',
    label: 'Principal Delegation',
    description: 'Manage availability and delegate to VP',
    icon: 'UserRoundCog',
    path: '/principal/delegation',
    roles: ['PRINCIPAL'],
    group: 'account',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'principal-search',
    label: 'Search Campus',
    shortLabel: 'Search',
    description: 'Search students, faculty and records',
    icon: 'Search',
    path: '/principal/search',
    roles: ['PRINCIPAL'],
    group: 'overview',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'principal-profile',
    label: 'My Profile',
    shortLabel: 'Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/principal/profile',
    roles: ['PRINCIPAL'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 4,
  },

  // ====================================================
  // VICE PRINCIPAL ROUTES
  // ====================================================
  {
    id: 'vp-dashboard',
    label: 'VP Operations',
    description: 'Operations overview and delegated approvals',
    icon: 'LayoutDashboard',
    path: '/vp/dashboard',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'vp-leave-approvals',
    label: 'Approvals & Workflows',
    description: 'Executive approvals and request workflows',
    icon: 'CircleCheckBig',
    path: '/vp/leave-approvals',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 2,
    badgeKey: 'pendingApprovals',
  },
  {
    id: 'vp-availability',
    label: 'Availability Board',
    description: 'Live campus availability',
    icon: 'RadioTower',
    path: '/vp/department-availability',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'management',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'vp-departments',
    label: 'Departments',
    description: 'Monitor department performance',
    icon: 'Building2',
    path: '/vp/departments',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'management',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'vp-placement',
    label: 'Placement Overview',
    description: 'Track placement and internship activities',
    icon: 'BriefcaseBusiness',
    path: '/vp/placements',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'vp-reports',
    label: 'Operations Reports',
    description: 'Institution-wide operations analytics',
    icon: 'ChartSpline',
    path: '/vp/reports',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'insights',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'vp-circulars',
    label: 'Circulars',
    description: 'View and manage circulars',
    icon: 'Megaphone',
    path: '/vp/circulars',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 1,
  },
  {
    id: 'vp-notifications',
    label: 'Alerts',
    description: 'Important alerts and notifications',
    icon: 'Bell',
    path: '/vp/notifications',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 4,
    badgeKey: 'unreadNotifications',
  },
  {
    id: 'vp-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/vp/profile',
    roles: ['VICE_PRINCIPAL', 'VP'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 5,
  },

  // ====================================================
  // PARENT ROUTES
  // ====================================================
  {
    id: 'parent-dashboard',
    label: "Child's Dashboard",
    description: "Overview of your child's academic status",
    icon: 'LayoutDashboard',
    path: '/parent/dashboard',
    roles: ['PARENT', 'parent'],
    group: 'overview',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'parent-attendance',
    label: 'Attendance',
    description: "Track your child's daily attendance",
    icon: 'ClipboardCheck',
    path: '/parent/attendance',
    roles: ['PARENT', 'parent'],
    group: 'academics',
    mobilePlacement: 'tab',
    order: 1,
  },
  {
    id: 'parent-marks',
    label: 'Academic Performance',
    description: 'View marks, results and performance trends',
    icon: 'ChartNoAxesColumnIncreasing',
    path: '/parent/marks',
    roles: ['PARENT', 'parent'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'parent-timetable',
    label: 'Timetable',
    description: "Your child's class schedule",
    icon: 'CalendarDays',
    path: '/parent/timetable',
    roles: ['PARENT', 'parent'],
    group: 'academics',
    mobilePlacement: 'more',
    order: 3,
  },
  {
    id: 'parent-fees',
    label: 'Fees & Payments',
    description: 'Pay fees and download receipts',
    icon: 'IndianRupee',
    path: '/parent/fees',
    roles: ['PARENT', 'parent'],
    group: 'requests',
    mobilePlacement: 'tab',
    order: 1,
    badgeKey: 'pendingFees',
  },
  {
    id: 'parent-messages',
    label: 'Messages',
    description: 'Messages from the mentor and college',
    icon: 'MessageSquare',
    path: '/parent/messages',
    roles: ['PARENT', 'parent'],
    group: 'communication',
    mobilePlacement: 'tab',
    order: 1,
    badgeKey: 'unreadMessages',
  },
  {
    id: 'parent-circulars',
    label: 'Circulars',
    description: 'College announcements and important notices',
    icon: 'Megaphone',
    path: '/parent/circulars',
    roles: ['PARENT', 'parent'],
    group: 'communication',
    mobilePlacement: 'more',
    order: 2,
  },
  {
    id: 'parent-profile',
    label: 'My Profile',
    description: 'View and edit your personal information',
    icon: 'UserRound',
    path: '/parent/profile',
    roles: ['PARENT', 'parent'],
    group: 'account',
    mobilePlacement: 'tab',
    order: 1,
  },
];

// Sidebar group labels per role display name
export const NAV_GROUP_CONFIGS: NavGroupConfig[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'monitoring', label: 'Monitoring' },
  { id: 'teaching', label: 'Teaching' },
  { id: 'academics', label: 'Academics' },
  { id: 'communication', label: 'Communication' },
  { id: 'management', label: 'Management' },
  { id: 'requests', label: 'Requests & Finance' },
  { id: 'responsibilities', label: 'Responsibilities' },
  { id: 'insights', label: 'Insights' },
  { id: 'career', label: 'Career' },
  { id: 'account', label: 'Account' },
  { id: 'system', label: 'System' },
];
