import React from 'react';
import { FileText, ChevronLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useInstitution } from '../../context/InstitutionContext';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using CampusOS ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to all these terms, you may not access or use the Platform. These terms apply to all users including students, faculty, staff, parents, administrators, and guests.`,
  },
  {
    title: '2. Platform Access and Accounts',
    content: `Access to CampusOS is granted exclusively by your institution. Your account credentials are personal and confidential. You are responsible for:

• Maintaining the confidentiality of your password
• All activities that occur under your account
• Reporting any unauthorized use to your institution immediately
• Ensuring your contact information is accurate and up to date

Accounts may not be shared, transferred, or used by anyone other than the authorized account holder.`,
  },
  {
    title: '3. Acceptable Use',
    content: `You agree to use the Platform only for lawful purposes and in accordance with these Terms. You must not:

• Use the Platform in any way that violates applicable local, national, or international laws or regulations
• Attempt to gain unauthorized access to any part of the Platform or its related systems
• Transmit any material that is defamatory, offensive, or otherwise objectionable
• Interfere with or disrupt the Platform's integrity or performance
• Use automated scripts, bots, or other means to extract data from the Platform without authorization
• Misrepresent your identity or impersonate any other person
• Upload or share content that infringes intellectual property rights`,
  },
  {
    title: '4. Academic Data and Records',
    content: `Academic records, grades, attendance data, and institutional documents available on the Platform are official records of your institution. You acknowledge that:

• These records are the property of the institution
• Data access is subject to your institutional role and permissions
• Any tampering with or falsification of academic records is a serious violation subject to institutional and legal action
• Official documents generated by the Platform are valid only as authorized by the institution`,
  },
  {
    title: '5. Payments and Fees',
    content: `Fee payments processed through the Platform are subject to your institution's fee policy. Refunds and disputes are governed by institutional rules. CampusOS facilitates payment processing but does not directly handle funds. Payment gateway security is provided by the configured third-party processor.`,
  },
  {
    title: '6. Intellectual Property',
    content: `The CampusOS Platform, including its software, design, features, and documentation, is protected by intellectual property laws. You may not:

• Copy, modify, distribute, or create derivative works from the Platform
• Reverse engineer or attempt to extract the source code
• Remove any proprietary notices or labels from the Platform

Institutional content (circulars, documents, course material) belongs to the respective institution or faculty member and is shared under institutional authority.`,
  },
  {
    title: '7. Availability and Maintenance',
    content: `We aim to maintain high Platform availability but do not guarantee uninterrupted access. The Platform may be temporarily unavailable due to scheduled maintenance, updates, or circumstances beyond our control. We will provide advance notice of planned maintenance where possible.`,
  },
  {
    title: '8. Limitation of Liability',
    content: `To the maximum extent permitted by law, CampusOS and your institution shall not be liable for:

• Indirect, incidental, special, or consequential damages arising from your use of the Platform
• Loss of data due to technical failures, provided reasonable backup procedures are maintained
• Decisions made based on information displayed on the Platform that has not been officially confirmed through institutional channels`,
  },
  {
    title: '9. Termination',
    content: `Your access to the Platform is tied to your institutional relationship. Access is automatically terminated upon your departure from the institution (graduation, resignation, or otherwise). Accounts may also be suspended or terminated for violation of these Terms, as determined by the institution.`,
  },
  {
    title: '10. Governing Law',
    content: `These Terms shall be governed by the laws of India. Any disputes arising from these Terms or your use of the Platform shall be subject to the exclusive jurisdiction of the courts in the jurisdiction where your institution is registered.`,
  },
  {
    title: '11. Changes to Terms',
    content: `We reserve the right to modify these Terms at any time. Updated terms will be posted on the Platform with a revised effective date. Continued use of the Platform after changes constitutes acceptance of the revised Terms.`,
  },
  {
    title: '12. Contact',
    content: `For questions about these Terms of Service, contact your institution's IT department or the CampusOS system administrator. For platform-level inquiries: legal@campusos.app`,
  },
];

export default function TermsOfServicePage() {
  const navigate = useNavigate();
  const { collegeName } = useInstitution();

  const effective = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b border-border bg-card sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="p-1.5 rounded-lg hover:bg-muted transition-colors text-muted-foreground"
            aria-label="Go back"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-primary" />
            <span className="text-sm font-semibold text-foreground">Terms of Service</span>
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-10">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-foreground">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mt-1">
            {collegeName} · CampusOS Platform
          </p>
          <p className="text-xs text-muted-foreground mt-1">Effective date: {effective}</p>
        </div>

        <div className="space-y-8">
          {SECTIONS.map((section) => (
            <section key={section.title}>
              <h2 className="text-sm font-bold text-foreground mb-2">{section.title}</h2>
              <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
                {section.content}
              </p>
            </section>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-border text-center">
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} CampusOS. These Terms apply to your use of the Platform at {collegeName}.
          </p>
        </div>
      </div>
    </div>
  );
}
