import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { Response } from 'express';
import { PdfWatermarkService } from '../../services/pdf-watermark.service';

export class ReportsService {
  async generatePDFReportBuffer(reportType: string, user: any, data: any): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers: Buffer[] = [];
        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => {
          const result = Buffer.concat(buffers);
          if (!result || result.length === 0 || !result.slice(0, 5).toString('utf-8').startsWith('%PDF-')) {
            return reject(new Error('Generated PDF report buffer is invalid or corrupt.'));
          }
          resolve(result);
        });

        // Apply institutional watermark across all pages
        PdfWatermarkService.applyWatermark(doc);

        // Header
        doc.fontSize(20).text('GEETORUS CAMPUSOS', { align: 'center', underline: true });
        doc.moveDown(0.5);
        doc.fontSize(14).text(`Report: ${reportType}`, { align: 'center' });
        doc.moveDown(1);
        
        doc.fontSize(10).text(`Generated By: ${user.firstName || 'Staff'} ${user.lastName || ''} (${user.role?.name || 'Staff'})`, { align: 'right' });
        doc.text(`Generated Date: ${new Date().toLocaleString()}`, { align: 'right' });
        doc.moveDown(2);

        // Body Content
        doc.fontSize(14).text('Institution Summary', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10).text(`Total Students: ${data.totalStudents || 0}`);
        doc.text(`Total Faculties: ${data.totalFaculties || 0}`);
        doc.text(`Total Departments: ${data.totalDepartments || 0}`);
        doc.moveDown(1.5);

        doc.fontSize(14).text('Department Data', { underline: true });
        doc.moveDown(0.5);
        
        if (data.departments && data.departments.length > 0) {
          const startX = 50;
          let currentY = doc.y;
          
          doc.font('Helvetica-Bold');
          doc.text('Code', startX, currentY, { width: 50 });
          doc.text('Department Name', startX + 60, currentY, { width: 250 });
          doc.text('Students', startX + 320, currentY, { width: 70 });
          doc.text('Faculties', startX + 400, currentY, { width: 70 });
          
          currentY += 15;
          doc.font('Helvetica');
          
          for (const dept of data.departments) {
            if (currentY > 750) {
              doc.addPage();
              currentY = 50;
            }
            doc.text(dept.code || 'N/A', startX, currentY, { width: 50 });
            doc.text(dept.name || 'N/A', startX + 60, currentY, { width: 250 });
            doc.text(String(dept._count?.students ?? 0), startX + 320, currentY, { width: 70 });
            doc.text(String(dept._count?.faculties ?? 0), startX + 400, currentY, { width: 70 });
            currentY += 15;
          }
        } else {
          doc.text('No department data available.');
        }

        doc.moveDown(2);
        doc.fontSize(10).text('*** End of Report ***', { align: 'center' });
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  async generateExcelReportBuffer(reportType: string, user: any, data: any): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = `${user.firstName || 'Staff'} ${user.lastName || ''}`;
    workbook.created = new Date();

    // Sheet 1: Summary
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Metric', key: 'metric', width: 25 },
      { header: 'Value', key: 'value', width: 20 }
    ];
    summarySheet.getRow(1).font = { bold: true };
    
    summarySheet.addRow({ metric: 'Report Type', value: reportType });
    summarySheet.addRow({ metric: 'Generated Date', value: new Date().toLocaleString() });
    summarySheet.addRow({ metric: 'Generated By', value: `${user.firstName || 'Staff'} ${user.lastName || ''}` });
    summarySheet.addRow({ metric: '' }); // spacer
    summarySheet.addRow({ metric: 'Total Students', value: data.totalStudents || 0 });
    summarySheet.addRow({ metric: 'Total Faculties', value: data.totalFaculties || 0 });
    summarySheet.addRow({ metric: 'Total Departments', value: data.totalDepartments || 0 });

    // Sheet 2: Department Data
    const deptSheet = workbook.addWorksheet('Department Data');
    deptSheet.columns = [
      { header: 'Dept Code', key: 'code', width: 15 },
      { header: 'Department Name', key: 'name', width: 40 },
      { header: 'Total Students', key: 'students', width: 15 },
      { header: 'Total Faculties', key: 'faculties', width: 15 }
    ];
    deptSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
    deptSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } }; // Indigo-600

    if (data.departments && data.departments.length > 0) {
      data.departments.forEach((dept: any) => {
        deptSheet.addRow({
          code: dept.code || 'N/A',
          name: dept.name || 'N/A',
          students: dept._count?.students ?? 0,
          faculties: dept._count?.faculties ?? 0
        });
      });
    }

    const uint8 = await workbook.xlsx.writeBuffer();
    return Buffer.from(uint8);
  }

  async generateCsvReportBuffer(reportType: string, user: any, data: any): Promise<Buffer> {
    const lines: string[] = [];
    lines.push(`"Report Type","${(reportType || 'Institution Report').replace(/"/g, '""')}"`);
    lines.push(`"Generated By","${(`${user.firstName || 'Staff'} ${user.lastName || ''}`).replace(/"/g, '""')}"`);
    lines.push(`"Generated Date","${new Date().toISOString()}"`);
    lines.push(`"Total Students","${data.totalStudents || 0}"`);
    lines.push(`"Total Faculties","${data.totalFaculties || 0}"`);
    lines.push(`"Total Departments","${data.totalDepartments || 0}"`);
    lines.push('');
    lines.push('"Department Code","Department Name","Students Count","Faculties Count"');

    if (data.departments && data.departments.length > 0) {
      for (const dept of data.departments) {
        const code = (dept.code || '').replace(/"/g, '""');
        const name = (dept.name || '').replace(/"/g, '""');
        const stu = dept._count?.students ?? 0;
        const fac = dept._count?.faculties ?? 0;
        lines.push(`"${code}","${name}","${stu}","${fac}"`);
      }
    } else {
      lines.push('"No records available"');
    }

    return Buffer.from(lines.join('\r\n'), 'utf-8');
  }

  // Backward compatibility dispatchers
  async generatePDFReport(reportType: string, user: any, data: any, res: Response) {
    const buffer = await this.generatePDFReportBuffer(reportType, user, data);
    const dateStr = new Date().toISOString().split('T')[0];
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Length', String(buffer.length));
    res.setHeader('Content-Disposition', `attachment; filename="Institution_Report_${dateStr}.pdf"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Cache-Control', 'private, no-store, max-age=0, must-revalidate');
    res.status(200).send(buffer);
  }

  async generateExcelReport(reportType: string, user: any, data: any, res: Response) {
    const buffer = await this.generateExcelReportBuffer(reportType, user, data);
    const dateStr = new Date().toISOString().split('T')[0];
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Length', String(buffer.length));
    res.setHeader('Content-Disposition', `attachment; filename="Institution_Report_${dateStr}.xlsx"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Cache-Control', 'private, no-store, max-age=0, must-revalidate');
    res.status(200).send(buffer);
  }

  async generateCsvReport(reportType: string, user: any, data: any, res: Response) {
    const buffer = await this.generateCsvReportBuffer(reportType, user, data);
    const dateStr = new Date().toISOString().split('T')[0];
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Length', String(buffer.length));
    res.setHeader('Content-Disposition', `attachment; filename="Institution_Report_${dateStr}.csv"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Cache-Control', 'private, no-store, max-age=0, must-revalidate');
    res.status(200).send(buffer);
  }
}
