import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { Response } from 'express';
import { PdfWatermarkService } from '../../services/pdf-watermark.service';

export class ReportsService {
  async generatePDFReport(reportType: string, user: any, data: any, res: Response) {
    return new Promise<void>((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });

        // Apply institutional watermark across all pages
        PdfWatermarkService.applyWatermark(doc);

        // Set response headers
        const dateStr = new Date().toISOString().split('T')[0];
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="Institution_Report_${dateStr}.pdf"`);

        // Pipe directly to response
        doc.pipe(res);

        // Header
        doc.fontSize(20).text('GEETORUS CAMPUSOS', { align: 'center', underline: true });
        doc.moveDown(0.5);
        doc.fontSize(14).text(`Report: ${reportType}`, { align: 'center' });
        doc.moveDown(1);
        
        doc.fontSize(10).text(`Generated By: ${user.firstName} ${user.lastName} (${user.role?.name})`, { align: 'right' });
        doc.text(`Generated Date: ${new Date().toLocaleString()}`, { align: 'right' });
        doc.moveDown(2);

        // Body Content
        doc.fontSize(14).text('Institution Summary', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10).text(`Total Students: ${data.totalStudents}`);
        doc.text(`Total Faculties: ${data.totalFaculties}`);
        doc.text(`Total Departments: ${data.totalDepartments}`);
        doc.moveDown(1.5);

        doc.fontSize(14).text('Department Data', { underline: true });
        doc.moveDown(0.5);
        
        // Simple Table-like format for Departments
        if (data.departments && data.departments.length > 0) {
          const startX = 50;
          let currentY = doc.y;
          
          doc.font('Helvetica-Bold');
          doc.text('Code', startX, currentY, { width: 50 });
          doc.text('Department Name', startX + 60, currentY, { width: 250 });
          doc.text('Students', startX + 320, currentY, { width: 70 });
          doc.text('Faculties', startX + 400, currentY, { width: 70 });
          
          currentY += 15;
          doc.font('Helvetica');
          
          for (const dept of data.departments) {
            if (currentY > 750) {
              doc.addPage();
              currentY = 50;
            }
            doc.text(dept.code, startX, currentY, { width: 50 });
            doc.text(dept.name, startX + 60, currentY, { width: 250 });
            doc.text(dept._count.students.toString(), startX + 320, currentY, { width: 70 });
            doc.text(dept._count.faculties.toString(), startX + 400, currentY, { width: 70 });
            currentY += 15;
          }
        } else {
          doc.text('No department data available.');
        }

        doc.moveDown(2);
        doc.fontSize(10).text('*** End of Report ***', { align: 'center' });

        doc.end();

        // pdfkit triggers finish on stream close
        res.on('finish', () => resolve());
        res.on('error', (err) => reject(err));
      } catch (err) {
        reject(err);
      }
    });
  }

  async generateExcelReport(reportType: string, user: any, data: any, res: Response) {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = `${user.firstName} ${user.lastName}`;
    workbook.created = new Date();

    // Sheet 1: Summary
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Metric', key: 'metric', width: 25 },
      { header: 'Value', key: 'value', width: 15 }
    ];
    summarySheet.getRow(1).font = { bold: true };
    
    summarySheet.addRow({ metric: 'Report Type', value: reportType });
    summarySheet.addRow({ metric: 'Generated Date', value: new Date().toLocaleString() });
    summarySheet.addRow({ metric: 'Generated By', value: `${user.firstName} ${user.lastName}` });
    summarySheet.addRow({ metric: '' }); // spacer
    summarySheet.addRow({ metric: 'Total Students', value: data.totalStudents });
    summarySheet.addRow({ metric: 'Total Faculties', value: data.totalFaculties });
    summarySheet.addRow({ metric: 'Total Departments', value: data.totalDepartments });

    // Sheet 2: Department Data
    const deptSheet = workbook.addWorksheet('Department Data');
    deptSheet.columns = [
      { header: 'Dept Code', key: 'code', width: 15 },
      { header: 'Department Name', key: 'name', width: 40 },
      { header: 'Total Students', key: 'students', width: 15 },
      { header: 'Total Faculties', key: 'faculties', width: 15 }
    ];
    deptSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
    deptSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } }; // Indigo-600

    if (data.departments) {
      data.departments.forEach((dept: any) => {
        deptSheet.addRow({
          code: dept.code,
          name: dept.name,
          students: dept._count.students,
          faculties: dept._count.faculties
        });
      });
    }

    // Set response headers
    const dateStr = new Date().toISOString().split('T')[0];
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="Institution_Report_${dateStr}.xlsx"`);

    await workbook.xlsx.write(res);
    res.end();
  }
}
