import { prisma } from '../../lib/prisma';
import { DocumentGeneratorService } from './document-generator.service';
import { logger } from '../../utils/logger';

export class LiveExportService {
  /**
   * Export Live Student Records to Excel (.xlsx)
   */
  static async exportStudentProfilesExcel(userId: string, userRole: string, departmentId?: string) {
    const whereClause: any = { deleted: false };

    // Apply Department Scoping for HOD / Faculty
    if (userRole === 'HOD' && departmentId) {
      whereClause.departmentId = departmentId;
    }

    const students = await prisma.student.findMany({
      where: whereClause,
      include: {
        department: true,
        program: true,
        course: true,
        semester: true,
        section: true,
        mentor: true,
      },
      orderBy: { createdAt: 'desc' },
    });

    const columns = [
      { header: 'Admission No', key: 'admissionNo', width: 16 },
      { header: 'First Name', key: 'firstName', width: 18 },
      { header: 'Last Name', key: 'lastName', width: 18 },
      { header: 'Email', key: 'email', width: 25 },
      { header: 'Department', key: 'department', width: 20 },
      { header: 'Program', key: 'program', width: 15 },
      { header: 'Semester', key: 'semester', width: 12 },
      { header: 'Section', key: 'section', width: 10 },
      { header: 'Mentor', key: 'mentor', width: 20 },
      { header: 'Status', key: 'status', width: 12 },
    ];

    const data = students.map((s) => ({
      admissionNo: s.admissionNo || 'N/A',
      firstName: s.firstName,
      lastName: s.lastName,
      email: s.email,
      department: s.department?.name || 'N/A',
      program: s.program?.code || 'N/A',
      semester: s.semester?.name || 'N/A',
      section: s.section?.name || 'N/A',
      mentor: s.mentor ? `Prof. ${s.mentor.firstName} ${s.mentor.lastName}` : 'Unassigned',
      status: s.status,
    }));

    const buffer = await DocumentGeneratorService.generateExcelWorkbook('Student Directory', columns, data);

    // Record Audit & ExportJob Log
    try {
      await prisma.documentDownloadAudit.create({
        data: {
          userId,
          userRole,
          action: 'EXCEL_EXPORT_GENERATED',
          documentType: 'STUDENT_EXCEL',
        },
      });
    } catch (_) {}

    logger.info(`📊 Live Student Excel Export generated by user ${userId} (${data.length} records)`);
    return { buffer, filename: `Student_Directory_${new Date().toISOString().split('T')[0]}.xlsx` };
  }

  /**
   * Export Live Faculty Records to Excel (.xlsx)
   */
  static async exportFacultyProfilesExcel(userId: string, userRole: string) {
    const facultyList = await prisma.faculty.findMany({
      where: { deleted: false },
      include: { department: true },
      orderBy: { createdAt: 'desc' },
    });

    const columns = [
      { header: 'Employee ID', key: 'employeeId', width: 15 },
      { header: 'First Name', key: 'firstName', width: 18 },
      { header: 'Last Name', key: 'lastName', width: 18 },
      { header: 'Email', key: 'email', width: 25 },
      { header: 'Designation', key: 'designation', width: 20 },
      { header: 'Department', key: 'department', width: 20 },
      { header: 'Joining Date', key: 'joiningDate', width: 15 },
      { header: 'Status', key: 'status', width: 12 },
    ];

    const data = facultyList.map((f) => ({
      employeeId: f.employeeId || 'N/A',
      firstName: f.firstName,
      lastName: f.lastName,
      email: f.email,
      designation: f.designation || 'Faculty',
      department: f.department?.name || 'N/A',
      joiningDate: f.dateOfJoining ? new Date(f.dateOfJoining).toLocaleDateString() : 'N/A',
      status: f.status,
    }));

    const buffer = await DocumentGeneratorService.generateExcelWorkbook('Faculty Directory', columns, data);

    try {
      await prisma.documentDownloadAudit.create({
        data: {
          userId,
          userRole,
          action: 'EXCEL_EXPORT_GENERATED',
          documentType: 'FACULTY_EXCEL',
        },
      });
    } catch (_) {}

    logger.info(`📊 Live Faculty Excel Export generated by user ${userId} (${data.length} records)`);
    return { buffer, filename: `Faculty_Directory_${new Date().toISOString().split('T')[0]}.xlsx` };
  }

  /**
   * Export Live CSV Data
   */
  static async exportStudentCsv(userId: string, userRole: string) {
    const students = await prisma.student.findMany({
      where: { deleted: false },
      include: { department: true, program: true },
      take: 500,
    });

    const headers = ['Admission No', 'Name', 'Email', 'Department', 'Program', 'Status'];
    const rows = students.map((s) => [
      s.admissionNo || '',
      `${s.firstName} ${s.lastName}`,
      s.email,
      s.department?.code || '',
      s.program?.code || '',
      s.status,
    ]);

    const buffer = DocumentGeneratorService.generateCsvBuffer(headers, rows);
    return { buffer, filename: `Student_Export_${new Date().toISOString().split('T')[0]}.csv` };
  }
}
